### ISSUE TITLE
HTTP PUT vs POST for rotating access tokens

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#100]
§6.1 Rotating the Access Token: Editor's note: 

This could alternatively be an HTTP PUT verb, since we are telling the AS that we want to replace the token. However, we are not providing the information we want to replace the token with, and in fact that's up to the AS entirely, not the client. For that reason, I think a POST still makes the most sense.

**Comment by jricher** [comment]
Editors suggest keeping this function as POST as the semantics of the PUT verb do not match the function as described.

**Comment by TomCJones** [comment]
yes - let's close it.
