### ISSUE TITLE
JWS Headers for JOSE-based signature methods

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#106]
§8.1 Detached JWS: Editor's note: 

It's not the usual practice to put additional information into the header of a JWS, but this keeps us from having to normalize the body serialization. Alternatively, we could add all these fields to the body of the request, but then it gets awkward for non-body requests like GET/DELETE. 

§8.2 Attached JWS: Editor's note: 

It's not the usual practice to put additional information into the header of a JWS, but this keeps us from having to modify the body to use this signature method. Alternatively, we could add all these fields to the body of the request, but then it gets awkward for non-body requests like GET/DELETE.

**Comment by fimbault** [comment]
This is a design choice. What can't be done or what is made difficult by what is currently in the text? Please advise or will be closed.

**Comment by davidgtonge** [comment]
Needs to be referenced in #15 - there are definite trade-offs with the different signature options and they need to be considered
