### ISSUE TITLE
Detached-JWS header

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#107]
§8.1 Detached JWS: Editor's Note: 

This is a custom header field, do we need this? It seems like the best place to put this.

**Comment by TomCJones** [comment]
not sure i understand the full issue, but i do think that the header body and sig need to be together. In my world jws is synonymous with 3 part jose.

**Comment by jricher** [comment]
@TomCJones There are more ways to use JWS than the common "compact" format that you're referring to. This method uses detached JWS (RFC7797: https://tools.ietf.org/html/rfc7797) to sign the request body and keep the signature separate. 

However, this issue is specifically about defining a new header to carry the detached signature, not the issue of having a detached signature itself.

**Comment by fimbault** [comment]
No other option available, so leave it as is. If it needs to be changed, please propose the change.

**Comment by davidgtonge** [comment]
I think the signing methods need to be pulled out - each to their own spec. If the detached JWS option is being kept then there needs to be discussion on this.

**Comment by davidgtonge** [comment]
Related to #15
