### ISSUE TITLE
Fragility of JOSE-based signature methods

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#108]
§8.1 Detached JWS: Editor's note: 

This is a potentially fragile signature mechanism. It doesn't protect arbitrary headers or other specific aspects of the request, but it's simple to calculate and useful for body-driven requests, like the client to the AS. Additionally it is potentially fragile since a multi-tier system could parse the payload and pass the parsed payload downstream with potential transformations, making downstream signature validation impossible. We might want to remove this in favor of general-purpose HTTP signing, or at least provide guidance on its use.

**Comment by TomCJones** [comment]
i agree. I found that i needed multiple keys within a single grant request and so didn't think detached sigs were a good idea.

**Comment by fimbault** [comment]
Wrap into a more global security assessment issue. But currently it is expected that we keep the signature mechanism at least until we have a more consistent solution.

**Comment by davidgtonge** [comment]
This is also needs reference in #15 - its crazy that we have 6 options here
