### ISSUE TITLE
Key redundancy in DPoP method

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#111]
§8.4 Demonstration of Proof-of-Possession (DPoP): Editor's note: 

This method requires duplication of the key in the header and the request body, which is redundant and potentially awkward.

**Comment by davidgtonge** [comment]
I agree that this is tricky. I think that an extension to DPoP which supports http signing may need to allow a key to be passed by reference rather than by value.

**Comment by fimbault** [comment]
This is the nature of DPoP proof mechanism as it is today. No specific action to be done. 
Might need review #7 and #15 also.

**Comment by fimbault** [comment]
This is a design choice. What can't be done or what is made difficult by what is currently in the text? Please advise or will be closed.

**Comment by davidgtonge** [comment]
I'm ok for this to be closed for now, but #15 needs a lot of discussion - I suggest this ticket is closed but a link posted in #15
