### ISSUE TITLE
Resource Server Section

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#114]
§10 Resource Servers: Editor's note: 

This section is for discussion of possible advanced
functionality. It seems like it should be a separate document or set of
documents, and it's not even close to being well-baked. This also adds
additional endpoints to the AS, as this is separate from the token
request process, and therefore would require RS-facing discovery or
configuration information to make it work. Also-also, it does presume
the RS can sign requests in the same way that a client does, but
hopefully we can be more consistent with this than RFC7662 was able to
do.

**Comment by Denisthemalice** [comment]
Section 10 mentions:

> In some deployments, a resource server will need to be able to call the AS for a number of functions.

Calling back the AS, allows the AS to know to the existence of the RS. There are cases where the AS should be prevented to know which the RS is.

When doing "Token Introspection" (Section 10.1), the AS may communicate to the RS some privileges without the client (and hence the end-user) knowing it (and thus **_without the end-user consent_**). 

"Deriving a downstream token" (Section 10.2) is described to allow a RS to act as a client instance and request a derived access token for a secondary RS. This can be done without a recall to the AS, if the name of the service to which the first RS belongs to is included into the access token. See the issue #203 which contains more details on how to do it.

"Registering a Resource Handle" (Section 10.3. ) allows the AS to know which RSs are trusting it. This should be avoided for RSs as soon as there is no bi-lateral trust relationships with the AS. This should also be avoided to allow large scale developments. 
A RS trusts some ASs to some extent, but the ASs do not necesarilly need to know which RSs are trusting them.

Requesting Resources With Insufficient Access (Section 10.4) is addressed in another issue. 
See "Requesting resources with insufficient access" #203

The whole section would need to be re-written.

**Comment by jricher** [comment]
Section 10 is made of optional elements. Token introspection is not required, you could alternatively use a self-contained token. Deriving a token without the AS's involvement is deeply problematic for most use cases as the AS is the root of trust in the system and overriding that would subvert the security model. Yes, introducing the RS to the AS lets the AS know about the RS as this is the point.

**Comment by Denisthemalice** [comment]
(Section 10.4) Requesting Resources With Insufficient Access is NOT an optional element.
 Nevertheless, it is addressed in another issue.  See "Requesting resources with insufficient access" #203.
 
At the moment the text states:

> In some deployments, a resource server will need to be able to call the AS for a number of functions. 

The phrasing of section 10 should be reworded to indicate that the sub-sections 1, 2 & 3 describe optional functions.

You also wrote: "introducing the RS to the AS lets the AS know about the RS as this is the point". I do understand that this is necessary for some use cases, but not for all use cases, in particular when ACLs are used by the RS instead of capabilities

**Comment by jricher** [comment]
This section will be pulled out into a separate document, to be discussed by the working group. Note that in the future it could be re-incorporated into the core if the working group decides to restructure things that way.
