### ISSUE TITLE
Stable URL for “Display of a Short User Code”

### ISSUE THREAD

**Issue by aaronpk** [ietf-wg-gnap/gnap-core-protocol#123]
In the section “Display of a Short User Code” it says the URL *MUST* be stable so that the client can be statically configured with it. This seems to contradict the idea of returning the URL in the response here especially since the URL isn’t even required. Either the client is statically configured with a URL and so it doesn’t need the URL in the response, or the client needs the URL in the response because it is not statically configured. It seems the MUST is too restrictive here.

**Comment by jricher** [comment]
The normative language might need to be tweaked here, but some background could help: This is based off of similar requirements in [OAuth Device Grant](https://tools.ietf.org/html/rfc8628) as this takes the place of the `verification_uri`. Note that the equivalent of `verification_uri_complete` is just to use the `redirect` interaction method, which allows us to avoid the security issues enumerated in that RFC around that function.

**Comment by jricher** [comment]
Proposal change set: create a three-tier interaction start method to handle different use cases with different dynamic portions:

- long arbitrary URL, suitable for QR code or browser redirect
- short arbitrary URL plus user code, suitable for things like set-top boxes that can't rely on QR codes on secondary devices and can't redirect
- user code alone, no URL included in the response; URL the user is sent to is static; suitable for limited interaction devices like voice-only interfaces that can't show a different URL at runtime

This would probably change the name of the `redirect` start mode, remove the `uri` from the `user-code` start mode, and create a new kind of start mode that has both dynamic URL and user code in the response.
