### ISSUE TITLE
Generic claim extension mechanism

### ISSUE THREAD

**Issue by fimbault** [ietf-wg-gnap/gnap-core-protocol#131]
Related to #64 (OpenID connect) but able to support also other schemes (e.g. VC), and related query syntax
Most probably by extensions

**Comment by fimbault** [comment]
To revisit when we have something concrete

**Comment by jricher** [comment]
This discussion gets us close into the identity protocol space, and the method for defining this should be a part of the extensions discussion in #134

**Comment by fimbault** [comment]
This could help https://www.slideshare.net/TorstenLodderstedt/openid-for-verifiable-credentials-iiw-35 

Seems fairly straightforward to extend assertions formats and responses, although I'm wondering whether we should also include a type for assertions
