### ISSUE TITLE
Guidance for Extensions

### ISSUE THREAD

**Issue by fimbault** [ietf-wg-gnap/gnap-core-protocol#134]
regrouping #65 #61 and #80 to provide guidance

**Comment by yaronf** [comment]
I would appreciate more detail here:
- A finite list of specific extension points that we want to enable (additional claims in the request? in the response?). IMO supporting too many extension points leads to code complexity, hence security issues. It also makes it harder to formally verify the protocol.
- Features that we trimmed and that we'd like to enable to reinstate if someone cares about them (maybe signature methods?).
- Additional requirements (having named extensions? allowing a protocol party to declare that one or more extensions are critical?).

We should aim for a strict protocol definition (e.g. messages can be validated using JSON Schema) where implementations refuse to accept unexpected "stuff", and only allow very specific places where additional "stuff" is acceptable. This may not be best practice for JSON-using protocols, but it is for security protocols.

**Comment by yaronf** [comment]
I agree with @fimbault  in principle, but let's not go too far. I think that SAML2 is functionality that'll be widely used from day one (correct me if I am wrong). If so, it needs to stay in the core spec.

**Comment by fimbault** [comment]
After discussion between editors, that's currently what will be proposed (draft8 includes the related security considerations).

Remains the question of JOSE, which will be discussed at IETF112. Personally I believe a separate draft would make sense (detached and attached JWS could be used by the oauth community as well) and it would also be easier to rally people that dislike JOSE to the GNAP WG. I short we'd be agnostic to those subjective assessments

**Comment by jricher** [comment]
Editors will list all intended extension points within Core, probably pulling together all the existing stubs for extensions in different sections into a larger discussion. This would require at least a shell of the IANA section for creating necessary registries.

**Comment by jricher** [comment]
Closed by #436
