### ISSUE TITLE
security assessment of the protocol

### ISSUE THREAD

**Issue by fimbault** [ietf-wg-gnap/gnap-core-protocol#135]
- formal analysis of the security of GNAP
- review existing methods, for instance #108 (we know it's fragile but many people use JOSE)

**Comment by jricher** [comment]
Formal analysis has been started by @pq2 et al, results will be incorporated into document when available via text or reference.

**Comment by fimbault** [comment]
Great work by Florian https://elib.uni-stuttgart.de/handle/11682/12220 that provides a security assessment of GNAP. This closes the issue. We can reopen it if we have specific items to cover.
