### ISSUE TITLE
Persistent Grant Identifier

### ISSUE THREAD

**Issue by fimbault** [ietf-wg-gnap/gnap-core-protocol#146]
Several contributors (Dave, Warren) asked whether there should be a **persistent identifier** of the grant.
See discussion on the mailing list as a starting point https://mailarchive.ietf.org/arch/msg/txauth/RB4u0uHS5SXSd3ngubBSuOkTC3s/ (Warren)
https://mailarchive.ietf.org/arch/msg/txauth/Txc1Y6HMSCA2-0sWP7h6GL3HbO4/ (Dave)

Before we dive into a potential technical solution, we should review the related use cases. Is it a problem if we don't have an identifier (or more precisely does it need to be exposed) ? What kind of operations would we do with it ?

**Comment by fimbault** [comment]
I guess that would mean that we'd provide a uri specific to the grantid, for instance 
generated through https://github.com/ai/nanoid => grantID = "FF0faxylE7ece_WpZNmeW"

"continue": {
        "access_token": { xxxx }
        "uri": "https://server.example.com/FF0faxylE7ece_WpZNmeW"
    }

??

**Comment by jricher** [comment]
The URI for the grant API needn't be the same as the identifier for the ongoing grant itself, and I don't see a good argument for forcing these two concepts to be tied together. Currently the access token is being used as an identifier, and I don't see a good reason for that being tied together either. Perhaps we need something as simple as a separate identifier?

**Comment by fimbault** [comment]
Yes, it's a possibility, the question is: what will this identifier be used for, precisely? (see issue #62 too)

**Comment by jricher** [comment]
So far that use case (extending and referencing an existing grant) is the only use case I've seen for an externalized identifier. That function was put in as an effort to support some of the advanced use cases that have been brought up. 

It's possible that this is a separable function that could go into an extension.

**Comment by davidgtonge** [comment]
So use cases for grant identifiers, getting an existing grant status, etc. are:

1. Allowing a client to update an existing grant
2. Getting a status of a grant from the AS - e.g. how long left before access expires (this can be dynamic in some environments and is useful for the client to know)

Some work underway in this area (with a customer requirement): https://bitbucket.org/openid/fapi/src/master/Financial_API_Grant_Management.md
https://openbankinguk.github.io/read-write-api-site3/v3.1.7/resources-and-data-models/aisp/account-access-consents.html#get-account-access-consentsconsentid

**Comment by fimbault** [comment]
Interesting. The grant management API in the fapi document doesn't allow updates, only queries and revoke, though.

**Comment by jricher** [comment]
@davidgtonge We can do most of those things without having an explicit external grant identifier, it all depends on how the API to do these actions is designed.

**Comment by jricher** [comment]
A grant identifier is not needed in the core protocol. However: editors suggest to write a small companion extension specification to define the use of a grant identifier and an "existing grant" reference to be used for a new request. See also #62
