### ISSUE TITLE
Token Binding

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#15]
Yaron: Why is key binding of the access token even optional?

Justin: Because people still want to use bearer tokens as an option. I think we can make bound tokens first class citizens in GNAP, and that’s a large reason behind having consistent key binding approaches instead of having them separated out (section 8). I think we can even make the “default” having the token bound to the RC’s presented key (and therefore make “unbound token” a flag instead), but I don’t think there would be support in the community for removing bearer tokens entirely.

Yaron: So let's pick one method, and make it mandatory-to-implement and "default". Terminology: I think the common usage is to talk about "token binding (to a key)" rather than "key binding (to what?)".

**Comment by davidgtonge** [comment]
I agree that there should be one default method, defining 6 methods seems over the top?

I hadn't realised that this draft proposes DPoP with an additional claim for the digest - we are working on something similar in the FAPI WG at the moment.

Mutual TLS is hard to require as mandatory to implement as it mixes application and transport layer concerns, so I would suggest `dpop` or `jws` be the default as they can be implemented purely at the application layer and use standard JWTs.

**Comment by jricher** [comment]
Related: tokens being bound to the client's key are made the default mode in #162, bearer tokens are still possible by passing in a flag.

**Comment by jricher** [comment]
Bound tokens are the default throughout, MTI considerations tracked under #7
