### ISSUE TITLE
Create JSON Schema

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#166]
To facilitate developers creating implementations, we should include a formal schema of the protocol, such as using JSON Schema (https://json-schema.org/), CDDL (https://tools.ietf.org/html/rfc8610), or a similar description language. 

This schema should not be a normative requirement for implementation but should help developers who choose to use it.

Initial attempt in PR #4 

See polymorphism discussion in #6 for some motivation.

**Comment by yaronf** [comment]
I most strongly suggest not to touch CDDL. See https://github.com/anweiss/cddl/issues/84#issuecomment-768631993 and his response.

**Comment by fimbault** [comment]
Ok but we'll still need to cover CBOR at some point

**Comment by fimbault** [comment]
An additional reason to support json schema (alignment with openapi) https://www.openapis.org/blog/2021/02/18/openapi-specification-3-1-released

**Comment by jricher** [comment]
I don't think it's worth the effort to create a full JSON schema, but it would be a good resource if it did exist.

**Comment by fimbault** [comment]
Will put that in https://github.com/ietf-wg-gnap/gnap-core-protocol/wiki/Implementation-guidelines#json-schema

**Comment by fimbault** [comment]
Json schema added for the request (based on 2020-12)

**Comment by jricher** [comment]
Oops, just saw that the schema only has request -- reopening to track the rest

**Comment by fimbault** [comment]
yes, response is under way too ;-)

**Comment by fimbault** [comment]
Added response
