### ISSUE TITLE
User-to-user delegation

### ISSUE THREAD

**Issue by fimbault** [ietf-wg-gnap/gnap-core-protocol#169]
In most cases, we have one client and we use JWT tokens. 

But we may encounter more advanced use cases, such as those described by agropper 

> I'm playing catch-up here so please bear with me. Yes, the end-user and resource owner are separate. In this use-case the resource owner's client is irrelevant because they have delegated authority to respond to requests to an authorization server. In this use-case the end user is using two different clients as part of the interaction process. One client is a true user agent, the other client is an agent of some other entity. The client that interacts with the authorization server is logically and maybe legally separate from the client that interacts with the resource server. Optionally, the end-user that began the interaction with the authorization server may delegate their authorization to another end-user that will actually access the resource with a different client. Finally, in this use-case, the resource server may seek signed software statements from the client presenting the authorization. Those software statements may or may not also be shared with the authorization server as part of the interaction.

>The issue of delegation among end-users has been a hot topic in credential and storage W3C workgroups. Here, for example is one thread with over 100 messages. There are many others and the issue is far from resolved. My goal is harmony between W3C data models and GNAP. I've created a very concise model for [six use-cases](https://docs.google.com/presentation/d/1ksKal62ZiApX09Nejm4RSqHzHJbgwpu_l2Ho64_ePKU/edit#slide=id.p) that may be helpful here as well. The use-case we're discussing [here is on Slide 10](https://docs.google.com/presentation/d/1ksKal62ZiApX09Nejm4RSqHzHJbgwpu_l2Ho64_ePKU/edit#slide=id.gb2d2b0f28a_0_313). In due course, we may choose to consider harmony on the other use cases as well, such as SIOP authentication.

I believe biscuit tokens could be a good fit for this kind of delegation, as an alternative to JWT. 
See https://biscuitsec.org and https://github.com/CleverCloud/biscuit (the project is reaching v1.0 soon).

**Comment by agropper** [comment]
Are ZCAP-LD https://w3c-ccg.github.io/zcap-ld/ equivalent to biscut in this context? 

Would the AS offer a choice of tokens to the client in cases where the client knew they need delegation capability or would the client specify the token format as part of the request?

**Comment by fimbault** [comment]
That's based on similar ideas (ocaps). Biscuits are not based on linked data though. 

I think it would be a good thing to enable innovation on tokens, as since we handle tokens as opaque, this is entirely possible. But of course we need to see the use cases first.

**Comment by agropper** [comment]
The healthcare use-case is pretty obvious. 
- A credentialed user (Dr. Bob) RP uses a secure wallet (capable of a non-repudiable signature) to make a request (RP credentials, scope of resource server access, purpose of access) to Alice RO's authorization server.
- The AS responds with a scoped capability and holds Bob accountable for its invocation.
- Dr. Bob passes that capability to his employer institution as part of a workflow where it shows up on a list.
- Dr. Bob may attenuate the capability before or after it is passed to the employer system.
- Dr. Carol is signs-in to the employer system and clicks on the capability associated with Alice on the list.
- The list, as RC, presents the capability to the RS and gains scoped accesses to the resource.
- RS and/or AS policy MAY require an audit trail that includes Carol's credentials and/or the root of trust of a software statement presented by the RC.

**Comment by fimbault** [comment]
Yes that would work.

**Comment by fimbault** [comment]
In the core, take the approach that the client library shouldn't care
But there's room for a additional document that defines a common structure

**Comment by fimbault** [comment]
The answer is twofold : 
- part of the discussion relates to #175 
- token formats are handled through the RS draft, if more is required, then we should open an issue there
