### ISSUE TITLE
Security of AC-provided Identifiers

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#17]
**Yaron**: what's the benefit of including a URI (URL really) in "display"? Do we really want the user (RO) to click links provided by the RC?

**Justin**: I think we want to give them the option of doing so, yes. It’s up to the AS to help protect the RO, and that will need to be written up in the security considerations. 

This is analogous to “client_uri” in OAuth Dynamic Registration: https://tools.ietf.org/html/rfc7591#section-2

Similarly **Yaron** 2.3.3: For obvious security reasons, I suggest adding: The AS MAY choose to avoid displaying an arbitrary URI. RC developers must only assume that the "name" field will be displayed.

**Justin**: I would actually go farther in the security considerations and say that not even the name is necessarily trusted for display. An RC could claim “Google Docs” as its display name, and without other information being displayed (like callback URIs or home pages), the RO’s got nothing to go on to figure out if it’s really Google Docs or not.

**Comment by jricher** [comment]
This has been covered by the security considerations section: https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-10.html#name-client-instance-impersonati
