### ISSUE TITLE
Rename DPoP digest parameter

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#173]
The FAPI WG is proposing a similar DPoP profile:

https://bitbucket.org/openid/fapi/src/master/Financial_API_Simple_HTTP_Message_Integrity_Protocol.md#markdown-header-522-dpr-dpop-request-signature-hash

This uses the `htd` field instead of `digest`, and we could align with that.

**Comment by fimbault** [comment]
Convergence would be helpful, do we know the status of the document?

**Comment by yaronf** [comment]
Is this something that can be standardized in `draft-ietf-oauth-dpop`, even as a best practice or recommendation? Trying to align with all documents out there is not a long time strategy...

**Comment by jricher** [comment]
I've reached out to the OAuth WG on the topic of defining the field in DPoP itself. If that happens we can remove this field from our spec, but until that happens then it makes sense to keep FAPI and GNAP aligned, for now.

**Comment by adeinega** [comment]
Regarding alignment between FAPI and GNAP... DPoP describes "htu" as

> The HTTP URI used for the request, without query and fragment parts.

while GNAP as

> The HTTP URI used for this request, including all path and query components.

which obviously isn't the same.
