### ISSUE TITLE
Protocol rationale

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#176]
For the RFC to be self-contained, please add a section to the Introduction (or an appendix) summarizing the main changes from OAuth2/OIDC, and the rationale for each delta.

(Originally raised by @agropper).

**Comment by fimbault** [comment]
Suggest to put this area in the wiki to have a deeper explanation

**Comment by jricher** [comment]
I've started a wiki page with some content I had written up for another publication: https://github.com/ietf-wg-gnap/gnap-core-protocol/wiki/Differences-from-OAuth-2

**Comment by yaronf** [comment]
This information is important to the draft's readership, and people are not seeing it (e.g., Denis's mail from March 26). Can we include it as-is in an appendix to the draft?

**Comment by fimbault** [comment]
I will submit a PR as an appendix. 
Note also that the editors prepared an article "Managing authorization grants beyond OAuth 2" that has been accepted at [OID2021](https://oid2021.compute.dtu.dk/)
