### ISSUE TITLE
Protected and Public Resources

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#185]
Implicitly and currently, only protected resources accessible using an access token are being considered. 

This is limitative, since it is possible for a client to first access to public information managed by a RS which is, by definition, unprotected. 

It is also possible for a client to access to protected resources managed by a RS by authenticating strongly to the RS, i.e. without presenting an access token.
 
A difference between these three cases should be made. When a client has never contacted a RS, it may wish to know whether the resource he wants to access is :

    (1) public, 
    (2) is protected using some strong authentication mechanism or 
    (3) is protected by the means of an access token. 

If the client has not been fully instructed on how to proceed, it should optionally be able to query the RS using an optional pre-flight discovery scheme. 

See a related issue about a" Tentative proposal for a RS discovery mechanism".

It should also be noted that if the client has been instructed on how to proceed a few years ago, the conditions might have changed and the optional mechanism provides a way to continue the processing with any disruption and without the need to perform a prompt client software update.

**Comment by fimbault** [comment]
It's true that we currently assume the RS endpoint is protected (that's the main point of a protocol such as GNAP), but from a developer's perspective, it's entirely possible that you would first try as if the resource was public and then start the negociation to get access. That's even much more likely in GNAP than in OAuth2, since you don't formally need a client_id.

**Comment by Denisthemalice** [comment]
You wrote: " _it's entirely possible that you would first try as if the resource was public and then start the negociation to get access_".

Between a public resource and a resource protected by the use of an access token, there is one additional possibility: the need for the end-user to authenticate to the RS ( i.e. without using any access token).

The most important section which should be updated is section 9.4. (Requesting Resources With Insufficient Access) where the various types of errors should be mentioned (401 to 405). See the issue #203 which provides the material to rewrite that section.

The note placed under the definition of a Protected Resource should be removed.

"Protected Resource 

protected API (Application Programming Interface) served by a RS and that can be accessed by a client, if and only if a valid access token is provided.

**Note: to avoid complex sentences, the specification document may simply refer to resource instead of protected resource.**"

The definition of a Protected Resource is also incorrect, since a resource can be protected using an **authentication** mechanism rather than an **authorization** mechanism.

A **Resource** is an (Application Programming Interface) served by a RS.

The above definition should be added. 

Some data objects of the resource may be public, some others may be accessible either (1) once an end-user has been authenticated or (2) once an end-user has presented an appropriate access token or (3) once an end-user has been authenticated and has presented an appropriate access token.

**Comment by jricher** [comment]
Resources that aren't protected by GNAP are out of scope of this specification. Even when processing a call without an access token, the specification only specifies what a GNAP protected resource's response would be. Other resources, including public resources and those protected by other authn/authz mechanisms, are out of scope and widening our definitions as suggested here would be confusing and not helpful.

**Comment by fimbault** [comment]
I agree with @jricher that the need for the end-user to authenticate to the RS ( i.e. without using any access token) seems really out of scope, since GNAP is the place where you issue and manage those access tokens.

**Comment by Denisthemalice** [comment]
The need for the end-user to authenticate to the RS ( i.e. without using any access token) is a common use case. 

GNAP certainly needs to focus on the use of access tokens, but this does not prevent the document to provide the full picture. 

At the moment the document is fully silent about the error codes that may be returned (and there is more than one, even when focusing on GNAP only). 

When writing code, the developer should be aware of the errors that can be reported when a call is being made. Theses error codes should be mentioned within the document and it is important to indicate which ones have precedence over the others. 

Writing code to handle the normal case takes 20 % of the effort, while writing code to handle all the error cases takes 80 % of the effort. 

:-)

**Comment by Denisthemalice** [comment]
This issue has been marked "Pending Close", however its content is fundamental.

**_@jricher:_** You wrote:

> One method of resource server responses to unauthenticated requests are discussed in GNAP-RS created by #246

The issue #246 does not contain wordings like **_unauthenti_** or **_authenti_** so I really wonder how #246 can address this issue.

This issue should not be closed
