### ISSUE TITLE
Requesting Resources With Insufficient Access

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#193]
In section 9.4, the text states: 

"If the client instance calls an RS without an access token, or with an invalid access token, the RS MAY respond to the client instance with an authentication header indicating that GNAP needs to be used to access the resource". 

This response is adequate only when a single AS is being considered. However, the response should be able to support the context of more than one AS and should allow the client to likely succeed in its next attempt. 

The protocol should also allow the end-user to indicate his consent whereas this is not the case presently when using an opaque handle. 

The response should be able to include the same parameters as those described under the Issue "Tentative proposal for a RS discovery mechanism" #190.

**Comment by fimbault** [comment]
same as #203?

**Comment by Denisthemalice** [comment]
Yes, indeed.

**Comment by fimbault** [comment]
Closing as duplicate
