### ISSUE TITLE
Requesting User Information

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#197]
In section 2.4 (Requesting User Information), the first sentence starts with:

     If the client instance is requesting information about the RO from the AS, ...

From the title, the acronym "RO" should be changed into "end-user". The case where the RO is also the end-user is a specific case. 

This leads to the following change:

     If the client instance is requesting information about the end-user from the AS, ...

In the following sentences of this section, RO should be changed into end-user.

**Comment by fimbault** [comment]
The current text really means RO, and that's not illogical considering most of what is explained only considers the case end-user = RO. 
Any other case would even trigger an error: "If the identified end-user does not match the RO present at the AS during an interaction step, the AS SHOULD reject the request with an error." (section 2.4)

I think we should clarify when we could have a remote RO too.

**Comment by Denisthemalice** [comment]
The title has been changed into "Requesting Subject information". 
This title is incorrect as long as a subject can be also an organization or a device.

An AS can hold information about an end-user or about RO when the RO is a human being. It does not hold information about organizations or devices. However, an end-user may belong to some organizations or/and use some devices. 

IMO, I would replace it by "**Requesting end-user Information**". 
If an AS holds information about an end-user, it seems logical that the end-user should have access to it.

If it happens that the end-user has also a RO account on the AS, then it should also have access to it. 
In such a case, another section with the following title "**Requesting RO Information**" should be created.

RO = end-user was a common case in OAuth. In GNAP and in the general case a RO is different from an end-user and an AS may have no relationship with any RO (e.g. when attributes only are being used).

**Comment by fimbault** [comment]
I guess you refer to "2.2. Requesting Subject Information".
We might have to harmonize a bit, but for instance "2.3. Identifying the Client Instance" might very well hold information about devices or at least the software running on it (that's the point of client software attestation to be discussed in #44)

We don't always know in advance whether it will be a RO or an end-user only, so the proposal isn't always applicable.

**Comment by Denisthemalice** [comment]
I was indeed referring to "2.2. Requesting Subject Information" which has no relationship with "2.3. Identifying the Client Instance".

This means that your arguments do not apply to section 2.2. and, by implication, that my argumentation currently remains valid.

**Comment by fimbault** [comment]
Well, I take the point in consideration but I don't think we should base our reasoning on the structure of sections, which can change

**Comment by fimbault** [comment]
After quite a bit of thoughs on this, I think you're right, we should refer to the end-user (I'll explain why in detail in the upcoming discussion for IETF110, there will be a complete document).

**Comment by fimbault** [comment]
Having spent more time on this, I think we do need to clarify. Will be discussed at IETF110. 
There could for instance be a principal subject (the RO) and a delegated subject (the end-user).
