### ISSUE TITLE
Interaction "Modes"

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#20]
The word Mode has connotations of a predefined sequence of steps, like the OAuth2 "grant". If we decide to stick to the current model where you can make a la carte combinations of these "modes", we should rename them accordingly. E.g. "interaction capabilities" or "interaction properties". (Or "interaction things"...)

**Comment by jricher** [comment]
Would "interaction methods" fit better? With the current syntax, you're effectively creating a single "grant" out of all of the available components. The interactions available are the intersection of what the RC sets up and what the AS responds with.

Then if the multiple-interaction suggestion is incorporated (sending an array with closely-related items), each of those would roll up into an "interaction mode".

**Comment by jricher** [comment]
An alternative syntax for interaction requests is proposed in #59

**Comment by aaronpk** [comment]
I think this is okay as "modes" since each mode does specify a distinct action
