### ISSUE TITLE
"sub_id" claims

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#210]
Different types of sub_id claims have been identified in the presentation given at the IETF 110 virtual GNAP meeting.
 
This presentation is available at: 
https://datatracker.ietf.org/meeting/110/materials/slides-110-gnap-gnap-model-and-trust-relationships-00

A distinction between four types of "sub_id" claims has been made and it has important implications in terms of privacy 
(see the slides 9 to 12). The distinction is the following:

(1) "gu_id" a **globally unique identifier** (e.g. an email address, a social security number), 
(2) "as_id" an **identifier locally unique** to that AS for all the RSs, 
(3) "rs_id" an i**dentifier unique for every AS - RS pair**,
(4) "ses_id" a **temporary identifier for a single session** (i.e. a large random identifier). 

Below are some examples, using the new syntax defined in draft-ietf-secevent-subject-identifiers-07, 
published on March 9 th, 2021.

(1) For a globally unique identifier:
"sub_id": {
       "format": "gu_id",
       "gu_id": " email",
       "email: "john@hughes.com",
     }
or
"sub_id": {
       "format": "gu_id",
       "gu_id": "ssn",
       "ssn": { 
                    "cn": "250"
                    "value": "160087404506527",
                  },
     }

(2) For an identifier locally unique to that AS for all the RSs:
"sub_id": {
       "format": "as_id",
       "iss": "http://issuer.example.com/",
       "id": "john_hughes.com",
     }

(3) For an identifier unique for every AS - RS pair:
"sub_id": {
     "format": "rs_id",
     "iss": "http://issuer.example.com/",
     "id": "145234573478",
     }

(4) For a temporary identifier valid for a single session:
"sub_id": {
       "format": "session_id",
       "iss": "http://issuer.example.com/",
       "value": "A57B893E17F6471D",
     }

These sub_ids could be used as attributes into an access token (with or without using the "sub" claim),
 but would also be usable in ACLs (Access Control Lists).

**Comment by jricher** [comment]
1) I don't personally see what the second tier of formatting buys, since "email" would never be a "session_id". This is more suited to the privacy considerations around different identifier formats.

2) Subject identifiers, as used in GNAP, are between the AS and the client instance, the RS never sees this subject information.

**Comment by Denisthemalice** [comment]
**Answer to point 1**: All the proposal is indeed constructed to address privacy considerations.

**Answer to point 2**: The current draft is making the (silent) assumption that the user is also the RO.

The wording "Subject identifiers" is not defined in the vocabulary sections in the current draft.

There is however a sentence where this wording is used as the subject of the following sentence:

> Subject identifiers are hints to the AS in determining the RO and MUST NOT be taken as declarative statements 
> that a particular RO is present at the client instance and acting as the end-users.

In my presentation, I have addressed the general case where the RO != end-user.

I have also used the definition which is present at the top of Section 3 from draft-ietf-secevent-subject-identifiers.

  

>  A Subject Identifier is a JSON [RFC7159] object whose contents may be used to identify a subject within some context.  

This means that the rational of the comment 2 is not relevant.

Using the definition from draft-ietf-secevent-subject-identifiers, I believe that my last statement remains valid:

> These sub_ids could be used as attributes into an access token (with or without using the "sub" claim),
> but would also be usable in ACLs (Access Control Lists).

**Comment by fimbault** [comment]
Thanks @Denisthemalice for this classification of sub_ids, I think it makes sense.
Your remark on the integration of sub_ids into access tokens is interesting, although I'm not sure if GNAP is the right place to define the internals of how we map into the token itself. If the SECEVENT WG handles the relationship to JWT then it's a big win

**Comment by jricher** [comment]
The proposal here is the purview of the SECEVENT working group, GNAP will use the Subject Identifiers spec from that working group as-is.

**Comment by Denisthemalice** [comment]
This issue is marked "Pending Close", however its topic is important.

**_@fimbault_**: Thank you for your support. The classification of sub_ids is indeed important.

**_@jricher_** The SECEVENT list is rather silent for more than one month. 
I have posted a message that has still not been responded by the editors.

This topic should be unmarked from the marking " "Pending Close".

**Comment by aaronpk** [comment]
The reason for marking the issue "pending close" was stated above. If you have new information to bring to the issue we can continue the discussion.
