### ISSUE TITLE
Definition of a Resource Server (RS)

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#212]
The current definition in the draft is : 

> server that provides operations on **protected resources**, where operations require a **valid** access token issued by an AS.

What is a "valid" access token ? Is it a GNAP access token ? an OAuth access token ? a macaroon access token ? If it is a GNAP access token, does it mean that the received access token may have the right structure but may be incorrectly signed ? 

Instead of trying to respond to these questions, it is interesting to take a look at the definition used by ISO (https://www.iso.org/obp) for the same wording:

> resource server : computer that ultimately provides access to the object referenced by a specific client application request
> Source: ISO 24619:2011(en), 3.3.6

The ISO definition is not speaking of "protected resources" since the RS may host public resources, i.e. resources that are not protected. For those resources that are protected, the definition does not define how they are protected. They may be protected using some authentication mechanism or using some access tokens.

The current definition is using the wording " operations **on protected resources**" while the ISO definition is using the wording "operations **to objects**". In this context, the word "object" is more accurate and appropriate than the wording "protected resource".

In order to follow these observations, the following definition is being proposed:

> [Proposed definition]: server that provides operations to objects referenced by specific client application requests.

This has implications in the document mainly on the error codes that may be returned since some operations to some objects may be granted without the need to present any access token, or some operations to some other objects may be denied because the end-user has not been authenticated by the RS.

**Comment by fimbault** [comment]
a "valid" token is one for which the provenance can be proven (verify cryptographic signature) and that hasn't expired. The format doesn't matter. This is the kind of things we might want to cover in the security considerations, but there's nothing new for GNAP.
The ISO definition seems to broad and not specific to GNAP's context, in my view.

**Comment by jricher** [comment]
I agree with @fimbault to not accept the ISO definition here. Resources that are not protected by GNAP are not a concern of GNAP. Functions that services provide outside of GNAP are not a concern of GNAP.

**Comment by Denisthemalice** [comment]
**_@jricher_** : You wrote:

> Resources that are not protected by GNAP are not a concern of GNAP

The current definition of a RS in the draft is :

>    server that provides operations on protected **_resources_**, where operations require a **_valid_** access token issued by an AS

More accurately, a RS provides operations on **_protected objects_** (owned by one or more ROs) hosted by a RS.
 
The current definition also mentions "a **_valid_** access token issued by an AS". 
This seems to means a **_GNAP_** access token issued by an AS rather than a **_valid_** access token issued by an AS". 



When a client makes a **_first_** request to a RS, it does not necessarily know how this RS is protected, 
e.g. whether it is protected using OAuth 2.0 or GNAP, which access token format is supported, or 
whether this first request does not require any access token.
