### ISSUE TITLE
Definition and roles of a Resource Owner (RO)

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#213]
The current definition is :

> Resource Owner (RO) : “**_subject_** entity that may grant or deny operations on resources it has authority upon”.

The term "subject" in front of entity should be removed, since the term "subject" is used in the draft in different contexts where "subject" does not always designate the same kind of entity.

I thus propose the following definition where the word subject has been removed: 

> Resource Owner (RO) : “entity that may grant or deny operations on resources it has authority upon”.

Since there is no section with this title "Resource Owner" at the moment, the following text is proposed to be included into the draft into a new section dedicated to the Resource Owner. 

When the AS delivers a capability, it must cooperate with a RO able to deliver capabilities on objects of the RS under its control. 
In that case, the RO may either be a process or a human being.

A RS is in charge of the management a set of resources where the operations that can be performed on this set of resources are granted or denied by one or more ROs. 

Each RS supports an Access Enforcement Function (AEF) which follows access control rules established by an Access Decision Function (ADF) administered by **one or more a Resource Owners (ROs).**
 
These access control rules may be either ACL based and/or capability based. 

The ROs recognized by a given RS may be a process, a human being or a device (IoT case).

For each method requested by a client on an object, the rules enacted by an RO associated with a RS (only on resources it has authority upon) indicate which methods or operations may be granted. Some of these rules may allow the use of some methods without the need to present any access token (e.g. public access or access protected using an authentication mechanism), while some other rules may require one or more access tokens which may be or may not be GNAP access tokens.

When these rules are ACL based : they indicate which attribute types and attributes values issued by that AS must be presented to use a method on the object.

When these rules are Capability based : they indicate which methods issued by the RO from that AS must be presented to use a method on the object. 

IMPORTANT: When a RO associated with an AS delivers a capability on a resource under the control of a RS, that capability is analyzed and filtered by the ADF of the RS (i.e. the appropriate RO) which indicates which method(s) delivered by the RO associated with that AS can be accepted.

End of the proposed text.

Now, closing the loop:

When a RO is associated with an AS, the "entity" may either be process or a human being.
When a RO is associated with a RS, the "entity" may be a process, a human being or a device (IoT case).

**Comment by fimbault** [comment]
subject is important, because we're delivering information about it in our responses. So the current definition seems fine to me. 

For the clarification text about the RO: this adds a lot of terms that aren't used anywhere else (AEF, ADF, ACL, capabilities), I'm not sure it would help the unfamiliar reader. Plus there are a few assumptions I'm not sure everyone will agree with in the context of an authZ protocol (ex: "when RO associated to RS": of course it's possible that a RO has an account at the RS, but we don't assume anything related to that in the spec itself).

**Comment by jricher** [comment]
ACLs and identity-based access are just one of many models for protected resources, GNAP cannot be focused on only one such model and needs to remain agnostic to these aspects.
