### ISSUE TITLE
Simplify access token hash

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#216]
There have been several questions about the `at_hash` parameter currently used to convey the hash of an access token in requests to the RS. Right now we use the definition from OpenID Connect:

https://openid.net/specs/openid-connect-core-1_0.html#CodeIDToken

In speaking with the DPoP editors I've proposed a simplified claim there:

https://github.com/danielfett/draft-dpop/pull/62/

It's functionally similar but doesn't require the array truncation step, and it also fixes to a single hash algorithm (SHA-256) instead of having to figure out which hash to use based on the external signing envelope. I think this change makes it both simpler to implement and to understand.

**Comment by jricher** [comment]
Also, for cryptographic agility here we would rely on defining a new claim name and updating the requirements about inclusion. So `ath` would always be SHA-256 and once that hash is sufficiently broken and discarded we would define a new claim like `ath_but_good` for whatever new target there is.

**Comment by fimbault** [comment]
+1 for that, much more intuitive than truncating (and the comment from DPoP editors seem to go in that direction too). 
In relation to what would happen if SHA-256 gets deprecated: 
* the current method is already based on SHA-256, so it's not a new downside
* an idea would be to name it `ath2` for instance, to give a minimal versioning (would currently relate to SHA2) and would simplify changes later on (like avoiding `ath_but_good_better` ;-))

**Comment by jricher** [comment]
I personally think that naming the next version of the field should be left to the next version. Someone might want to specify `ath_sha3` or even `ath#sha3`, but the important thing is that we aren't defining `ath` plus parameters, we're just defining `ath` and anything else comes along as its own unique string. That kind of guidance can be written around the registry for the claim and how it'd get used.

**Comment by fimbault** [comment]
works too

**Comment by jricher** [comment]
@yaronf crypto agility would be provided by defining a new field entirely. The algorithm will not change for `ath`. This was discussed in the OAuth WG with DPoP's `ath` field which has the same semantics as this. I do not recommend we re-open this.

**Comment by yaronf** [comment]
I'm not asking to reopen it. Just to add a note in the text.

> Note that this signature depends on a specific cryptographic algorithm, SHA-256, in two ways: the `ath` hash algorithm is hardcoded, and computing the payload of the detached/attached signature also uses a hardcoded hash. A future version of this document may address crypto-agility for both these uses by replacing `ath` with a new header that upgrades the algorithm, and possibly defining a new header that indicates the body's hash method.

The IESG reviewers are bound to comment on this.
