### ISSUE TITLE
xml2rfc

### ISSUE THREAD

**Issue by fimbault** [ietf-wg-gnap/gnap-core-protocol#219]
This issue is not related to the spec itself, but to a build tool.
I don't know if I'm the only one to get that in local, but docker-compose fails to generate the html. 
TypeError: expected string or bytes-like object
(I don't know enough the tool to say if that's coming from me or not, especially with many lines of warnings and errors, if someone can tell me if they have the same issue after fetching upstream, that would be great / it seems the PR still builds fine so that may be coming from my local environment)

Here's the stack trace:

`md2rfc_1  | Traceback (most recent call last):
md2rfc_1  |   File "/usr/local/bin/xml2rfc", line 8, in <module>
md2rfc_1  |     sys.exit(main())
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/run.py", line 754, in main
md2rfc_1  |     writer.write(filename)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 265, in write
md2rfc_1  |     html_tree = self.html_tree()
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 243, in html_tree
md2rfc_1  |     html_tree = self.render(None, self.root)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 320, in render
md2rfc_1  |     res = func(h, x)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 657, in render_rfc
md2rfc_1  |     self.render(body, c)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 320, in render
md2rfc_1  |     res = func(h, x)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 334, in skip_renderer
md2rfc_1  |     self.render(h, c)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 320, in render
md2rfc_1  |     res = func(h, x)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 2341, in render_section
md2rfc_1  |     self.render(section, c)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 320, in render
md2rfc_1  |     res = func(h, x)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 2341, in render_section
md2rfc_1  |     self.render(section, c)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 320, in render
md2rfc_1  |     res = func(h, x)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 2341, in render_section
md2rfc_1  |     self.render(section, c)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 320, in render
md2rfc_1  |     res = func(h, x)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 2469, in render_t
md2rfc_1  |     self.render(p, c)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 320, in render
md2rfc_1  |     res = func(h, x)
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/writers/html.py", line 2788, in render_xref
md2rfc_1  |     if content and clean_text(x.text) != reftext:
md2rfc_1  |   File "/usr/local/lib/python3.9/site-packages/xml2rfc/utils.py", line 659, in clean_text
md2rfc_1  |     s = re.sub(r'[\u00a0\u2028]', ' ', s)
md2rfc_1  |   File "/usr/local/lib/python3.9/re.py", line 210, in sub
md2rfc_1  |     return _compile(pattern, flags).sub(repl, string, count)
md2rfc_1  | TypeError: expected string or bytes-like object`

**Comment by jricher** [comment]
I don't get this error on my system, even after rebuilding the docker image with `docker-compose up --build`. It's strange because docker image should be the same for everyone, that's kinda the point.

**Comment by fimbault** [comment]
precisely ;-) What's strange is that it worked before, I'll investigate. Thxs!

**Comment by fimbault** [comment]
I close the issue which seems local to my environment, if I find where that comes from I'll just add a comment so that I can be useful for others.

**Comment by fimbault** [comment]
Ok I purged my docker completely, and now it works.
