### ISSUE TITLE
Explicit typing for jws and jwsd key proofing mechanisms

### ISSUE THREAD

**Issue by adeinega** [ietf-wg-gnap/gnap-core-protocol#225]
The idea is to minimize ways to reuse JWS objects [for other purposes](https://tools.ietf.org/html/rfc8725#section-3.11). These attacks are sometimes referred as _Swapping JWTs_ and _Cross-JWT Confusion_). 

See also discussion in https://github.com/ietf-wg-gnap/gnap-core-protocol/pull/202.

**Comment by jricher** [comment]
Closed by #226
