### ISSUE TITLE
Unknown Extensions

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#23]
**Yaron**: The AS MUST ignore any unknown extension.

**Justin**: I’m OK with this stance, but it needs to be consistent throughout the protocol, not just at this level. 

**Yaron**: we can actually have one policy for an AS that doesn't understand something defined in the RFC (e.g. a token binding method) vs. extensions. Unknown extensions clearly must be ignored, otherwise you cannot deploy extensions incrementally. For RFC elements, this is more nuanced.

**Comment by jricher** [comment]
With the guidance on extension points from #436 and error codes from #385 and similar, this should now be covered by the current text.
