### ISSUE TITLE
Access token format(s) negotiation

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#239]
The access token format(s) supported both by the RSs and by the ASs should be advertised using some protocol 
(e.g. using a Discovery mechanism) so that a common format may be discovered by the clients and then be 
either advertised to a given AS or negotiated by the client with a given AS.

**Comment by fimbault** [comment]
Yes, that would be helpful as an extension.

**Comment by Denisthemalice** [comment]
Would you be able to come back on this issue, once a proposal for such an extension will be written ?
