### ISSUE TITLE
Unlinkability

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#241]
This topic falls under Privacy considerations but has consequences on the access token request protocol, hence it is opened as a separate thread. 

An end-user identifier present into an access token may be either:
1. a globally unique identifier (e.g. an email address, a social security number), or
2. an identifier locally unique to that AS for all the RSs, or
3. an identifier unique for every AS - RS pair, or 
4. a temporary identifier for a single access (i.e. a large random identifier).

In the case (1), if a same globally unique identifier is used by two or more ASs when issuing access tokens, 
all the RSs that receive access tokens from these AS will be able to link their user accounts.

In the case (2), if a identifier locally unique to the AS for all the RSs is used by the AS when issuing access tokens, 
all the RSs that receive access tokens from these AS will be able to link their user accounts.

In the case (3), if an identifier unique for every AS - RS pair is used by the AS when issuing access tokens, 
the RSs that receive these access tokens will be unable to link their user accounts.

In the case (4), if a temporary identifier for a single access (i.e. a large random identifier) is used by the AS when issuing access tokens, a single RS that receive these access tokens will be unable to know to which user it belongs.

Since an AS is unable to know which kind of end-user identifier should be used in a given context, the client should be able to indicate to the AS which type of end-user identifier shall be used when it is requesting an access token.

**IMPORTANT**: Some unlinkability properties may be ruined if the end-user authenticates to a RS using an authentication identifier 
that is globally unique identifier (e.g. an email address). This means that a great care should be given to the couple Authentication / Authorization.

**Comment by fimbault** [comment]
isn't it the same as #210?

**Comment by Denisthemalice** [comment]
No, even if the two issues are somewhat related.  

Issue #210 is intended to be placed in the main body of the document when parameters are being described 
(until these parameters are adopted by the SEC EVENT WG), while the text above is a candidate text to be included 
into the Privacy Considerations section.

**Comment by jricher** [comment]
Privacy considerations discussion moved to #249

Since access tokens are opaque to clients, clients do not have any input into the contents of the access token itself, including any inclusion or format of user identifiers.

**Comment by Denisthemalice** [comment]
This issue has been marked "Pending Close", however its content is fundamental.

**@jricher**. You wrote:

> Since access tokens are opaque to clients, clients do not have any input into the contents of the access token itself, 
including any inclusion or format of user identifiers.

This issue is not related to the access token format, but to what kind of information (in particular rights and/or attributes) 
will be placed into the access token, **_whatever its format may be_**.

We are no more in the case of OAuth where only a "scope" is being used to request an access token with a particular content.

An end-user should always be able to choose which attributes and optionally rights should be inserted into an access token. 
So at the time of making an access token request to an AS, a client should be able to indicate whether he wants :

-     a globally unique identifier (e.g. an email address, a social security number), or
-     an identifier locally unique to that AS for all the RSs, or
-     an identifier unique for every AS - RS pair, or
-     a temporary identifier for a single access (i.e. a large random identifier).

Such a description belongs to the core of the protocol. This does not prevent the "Privacy Considerations " section to provide
 some guidance or explanations. 









.
