### ISSUE TITLE
Privacy Considerations for Subject Identifiers

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#249]
Subject identifiers as used in GNAP have different privacy considerations based on their nature, this needs to be drawn out in extended privacy discussions within the core document. See #241 for some aspects of this.

**Comment by aaronpk** [comment]
This is discussed now in the [Correlation](https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-07.html#name-correlation) section in privacy considerations. New issues are welcome if there are additional privacy considerations to note that are not yet covered in this section.
