### ISSUE TITLE
Interaction (1) between the Client Instance and the RS as described in the first figure

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#252]
The text is as follows:

> (1) The client instance can attempt to call the RS (_**Section 10.4**_) to determine what access is needed. 
> The RS informs the client instance that access can be granted through the AS

**_Section 10.4_** is called: 10.4. Requesting Resources With Insufficient Access.

This is the very first exchange and its description comes in the very last section of the current draft which is placed within section 10 
which indicates: "In some deployments, a resource server will need to be able to call the AS for a number of functions."

**_Section 10.4 has nothing to do with a RS calling back the AS_**, but **_with a client instance calling a RS_**. 
So it is **_misplaced_** under section 10.

The description of the client instance attempting to call the RS should be placed within a section 1.4.1, 
i.e. **_before providing any "example"_**. The following exchanges, i.e. (2), (3), etc ... should be described after that first description
 in the same order within section 1.4.

Section 1.4.1 should be called : **1.4.1 First interaction between a client instance and a RS**.

In this first exchange, the client instance may request a resource either **_voluntarily_** "with Insufficient Access" or 
with a valid access token, if it already knows by experience or by other means the origin and the content of the access token 
that should be presented. 

This first exchange is fundamental because, depending upon the object and the method that are requested, either a single AS 
or more ASs may be trusted by the RO responsible of the object on the RS side. The key point is that there should be 
a "User Choice and consent" phase and also a "User Notice", if the client (in fact the end-user) wishes to be informed 
about the reasons before giving its consent.

The "User Choice and consent" phase as well as a "User Notice" are currently missing in the present draft. They should be added.

Since the first exchange is the most important and taking in consideration the goal of reducing the number of messages, that first exchange should also be usable to know which access token format(s) is supported by the RS. 

Note: It would not be appropriate to define in another document an additional message for supporting the discovery of access token format(s) supported by a RS.

**Comment by aaronpk** [comment]
This issue no longer applies, since the diagram referenced has been updated and no longer implies that the client has to call the RS. Section 10.4 will also be moved back into the core draft as being tracked by #260.
