### ISSUE TITLE
Format of defining REQUIRED vs OPTIONAL request/response elements

### ISSUE THREAD

**Issue by tplooker** [ietf-wg-gnap/gnap-core-protocol#257]
While reading through the latest draft, I found the expression of whether a request/response element is REQUIRED, OPTIONAL (or even perhaps conditional) is not very consistent. For instance in the top of [section 2](https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-05.html#section-2) nothing is defined about whether any of the top level request elements (access_token, subject, client, etc) are required or not? Whereas in later sections like [2.1.1](https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-05.html#section-2.1.1) definitions for sub-request elements like "flags" ends with a sentence "This field is OPTIONAL". And finally another convention is being used like in section [2.5.2](https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-05.html#section-2.5.2) where each request/response element definition starts with REQUIRED or OPTIONAL.

For general readability of the document I suggest using one explicit convention across the entire document for all request/response data model elements, the following rule might suffice.

For every request/response data model element, the definition should start with one of the following words OPTIONAL | REQUIRED | CONDITIONAL. If the definition is CONDITIONAL then the rest of the elements definition must stipulate the conditions under which the element will or will not be present.

**Comment by jricher** [comment]
I agree that consistency is better and more readable, and the editors will make an editorial pass to clean up things like this throughout the document. Note that CONDITIONAL is not a [BCP14](https://www.rfc-editor.org/info/bcp14) normative term, while REQUIRED and OPTIONAL both are, so we can't use the exact rule as suggested here.

**Comment by tplooker** [comment]
Thanks @jricher, agree this is purely editorial and therefore perhaps not high priority for the editors right now. However, w.r.t to conditional elements what do you propose the convention be for this? As even though the term CONDITIONAL is not defined under BCP14 some way to convey this meaning in an elements definition may be useful from a readability perspective.
