### ISSUE TITLE
Add an "implementation status" section

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#258]
Now is a good time to add this information into the draft, per https://tools.ietf.org/html/rfc7942.

Note that according to RFC 7942, this section will be removed before the protocol is published as an RFC.

**Comment by jricher** [comment]
Pending feedback from the IETF113 Hackaton, and discussion started here:

https://mailarchive.ietf.org/arch/msg/txauth/jD5rw3ycm3-t-e8Omad5uOOC5oI/

**Comment by fimbault** [comment]
Maybe this could go in https://github.com/ietf-wg-gnap/gnap-core-protocol/wiki/Implementation-guidelines instead of the core spec (since it is expected to be removed before publication anyway)
