### ISSUE TITLE
Should the reader understand that a RS can only be protected by a single AS ?

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#262]
In Section 1.4, The text states:

> (1) The client instance determines what access is needed and which AS to approach for access. Note that for most situations, the client instance is pre-configured with which AS to talk to and which kinds of access it needs.

The other cases that do not fall under the "most situations" are not described. In particular when the client does not know which AS**_s_** (note the plural) are trusted by the RS. How can an end-user make a choice between these Authorization Servers ?
Or should the reader understand that, in this model, a RS can only be protected by a single AS ?

**Comment by jricher** [comment]
While the RS may be protected by several AS's, the client is not given a choice of which AS to use. As previously discussed, you can propose an extension that defines this kind of discovery mechanism and see if there is support within the working group for it. Previously, there has not been support for this kind of mechanism.
