### ISSUE TITLE
Negotiation of the token format by the client should be mentioned in section 1.4

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#263]
When should/can **_the client_** use the _soon-to-be described protocol_ in draft-ietf-gnap-core-protocol 
to negotiate the token format between the AS and the RS ? 

This should be mentioned in section 1.4, even if the details are [I-D.draft-ietf-gnap-resource-servers].

**Comment by jricher** [comment]
As previously discussed many times, the client does not negotiate the token _format_. The token format and its contents are opaque to the client.
