### ISSUE TITLE
What kind of control may a client have about the content of a returned access token ?

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#265]
In section 1.4, the text states:

> (6) The client instance uses the access token (Section 7.2) to call the RS.

Shall the client blindly forward the access token to the RS ? 

What kind of control may a client have about the content of a returned access token before it is delivered by the AS to the client ?

If the client has no control, what are the implications in terms of the end-user privacy ?

**Comment by jricher** [comment]
1) Yes.

2) None.

3) End user privacy is protected and enhanced by not having the client look into the token or describe its contents.
