### ISSUE TITLE
The document is currently unable to follow the standards track 

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#276]
It is currently impossible to identify a subset of the protocols described in the document that would allow this document to follow the standards track 

RFC 2026 (Internet Standards Process) indicates on pages 11 and 12:

> Specifications that are intended to become Internet Standards evolve through a set of maturity levels known as the "standards track".  These maturity levels -- "Proposed Standard", "Draft Standard", and "Standard" -- are defined and discussed in section 4.1.
> 
> (…) 
> 
> 4.1.2 Draft Standard
> 
> A specification from which at least two independent and interoperable implementations from different code bases have been developed, and for which sufficient successful operational experience has been obtained, may be elevated to the "Draft Standard" level.
> 
> (...) 
> 
> The requirement for at least two independent and interoperable implementations applies to all of the options and features of the specification.  In cases in which one or more options or features have not been demonstrated in at least two interoperable implementations, the specification may advance to the Draft Standard level only if those options or features are removed.
> 

Frameworks should be progressed as Informational RFCs.

**Comment by jricher** [comment]
This is a protocol and not a framework.
