### ISSUE TITLE
No access token structure is being defined or referenced

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#277]
No access token format /content is being defined: its format and its content is a private agreement between ASs and RSs.

This issue is related to: Propose an access token model
https://github.com/ietf-wg-gnap/gnap-resource-servers/issues/15

The document does not define the content of access tokens, which makes impossible to specify how a RS shall verify an access token. Security of the exchanges cannot be verified and the pseudo-protocols are wide open to severe frauds, with on top of them “user collaborative attacks”.

At the minimum, the structure and the semantics of an access token should be defined, while its syntax would be left open 
(and defined in other documents).

**Comment by jricher** [comment]
This is covered in the RS document, closing this issue.
