### ISSUE TITLE
Trust relationships are still undefined

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#278]
The issue has been opened in March 2021 under the issue #214  and is still open:

However, protocols are directly dependent upon these trust relationships. 

Normally, one would expect that a RS can trust more that one AS for issuing access tokens that would contain some set of rights and/or attributes. Unfortunately, this is not presently the case.

The document assumes (without never saying it explicitly) a single bi-lateral trust relationship between a RS and an AS: a RS trusts one and only one AS. 

This has consequences in terms of scalability. In practice, such architecture will be restricted to cases where a given AS is recognized by a few hundred of RSs and not by a few millions of RSs. This may be adequate within a single organization but not for millions of RSs spread all over the world. 

In order to remove this limitation, an ACL model should also be supported where a RS would simply decide which types of attributes issued by a given AS can be trusted.

The current architecture is also be restricted to cases where a client instance is not allowed to present to a RS access tokens originating from two different ASs. There are use cases where such a functionality would be useful.

Unless these limitations are removed, they should clearly be advertised in the documents in order to allow other documents to cover these limitations.

**Comment by jricher** [comment]
Please do not copy other issues.
