### ISSUE TITLE
Trust relationships between ROs and ASs and between ROs and RSs are left undefined

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#279]
A Resource Owner (RO) is defined as a 

> “subject entity that may grant or deny operations on resources it has authority upon”. 

This is fine.

However, this definition does not imply that a RO necessarily interacts with an AS, which is what the document assumes. 
A note on page 8 states: 

> “an access token can be first issued to a client instance (requiring authorization by the RO) and subsequently rotated”.

This means that a RO associated with an AS is always mandated.

The document is rather vague about the trust relationship between a RS and a RO. 
It should be remembered that a trust relationship is defined in general as follows: 

-	an entity A trusts an entity B for some kind of action C. 

Buried in page 57, the following text provides a general explanation:

> The AS can sometimes determine which RO needs to consent based on what has been requested by the client instance, such as a specific RS record, an identified user, or a request requiring specific access such as approval by an administrator.

With such a haze, interoperability cannot be guaranteed.

In addition, a RS should not trust a RO for any kind of content included into an access token generated by a given AS, but only for some limited and specific rights and/or attributes. 

This double control is not addressed in the current document, whereas it should be.

**Comment by fimbault** [comment]
"an access token can be first issued to a client instance (requiring authorization by the RO) and subsequently rotated” is just a note in 1.3, and so is not a normative requirement.

The trust relationship is issue #214.

**Comment by fimbault** [comment]
Closing as duplicate
