### ISSUE TITLE
The access token is opaque to the client instance: transparency cannot be achieved

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#280]
On page 45, the text states: 

> The value of the access token as a string. The value is opaque to the client instance.

Under this assumption an important privacy property cannot be supported: **_transparency_**.
Without transparency, some users cannot be confident in using such a framework. 

Unless this limitation is removed, the lack of this privacy property should be advertised in the privacy considerations section.

**Comment by jricher** [comment]
Closing this issue as access token opacity has been previously discussed at length.

**Comment by aaronpk** [comment]
For future reference, this thread has the main discussion on this topic: #145
