### ISSUE TITLE
The client is unable to know that a RS is associated with more than one AS

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#281]
On page 103, section 9.1, the text states:

> The address of the GNAP endpoint MUST be sent in the "as_uri" parameter.

This means that a single GNAP endpoint is sent back by a RS.

This parameter should be changed to allow more than one GNAP endpoint to be specified.

**Comment by jricher** [comment]
As previously discussed, alternative discovery mechanisms can be proposed, for simplicity a single AS response was chosen to be represented. 

Closing this issue as this had been previously discussed.
