### ISSUE TITLE
The client has no effective control upon the content of an access token

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#282]
Despite the fact that an access token can contain "a set of rights and/or attributes", the client has no control upon the set of attributes that will be inserted into an access token.

On page 8, Grant is defined as:

> Grant (verb): to permit an instance of client software to receive some attributes at a specific time and valid for a specific duration and/or to exercise some set of delegated rights to access a protected resource

While this definition is correct, the document does not permit an instance of client software to only receive some chosen attributes at a specific time and valid for a specific duration.

The set of flags defined in section 2.1.1 on page 25 does not allow to request some set of attributes, since no attribute type is being defined.

"Useful" or "common" attribute types should be defined.

**Comment by jricher** [comment]
The access token is opaque to the client.

**Comment by aaronpk** [comment]
Previously discussed in #145
