### ISSUE TITLE
About the locations field

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#287]
In section 1.4, the locations field is missing. It is defined on page 97:

> locations (array of strings) The location of the RS as an array of strings. These strings are typically URIs identifying the location of the RS.

These strings are URLs identifying the location of the resource (i.e. not the location of the RS). 
The location of the RS may be inferred from the location of the resource.

Change into:

> locations (array of strings) The location of the resources as an array of strings. These strings are typically URIs, from which the location of the RSs may be inferred.

**Comment by jricher** [comment]
The strings could identify the rs or a specific resource, it's up to the AS and RS to determine that detail, which is why the text in question is an example.
