### ISSUE TITLE
Generic HTTP access control

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#303]
Proposed generic HTTP-based access control methods, described in mailing list thread: https://mailarchive.ietf.org/arch/msg/txauth/MJiaCD7DWESXnQ4YA7TlTyb8XOQ/

**Comment by yaronf** [comment]
Possibly as a separate document.

**Comment by jricher** [comment]
@yaronf Possibly so -- to start, the editors have decided to see if it works as a self-contained appendix to the core document, to be extracted later to another target if desired.
