### ISSUE TITLE
Asynchronous Authorization

### ISSUE THREAD

**Issue by davidgtonge** [ietf-wg-gnap/gnap-core-protocol#31]
I wonder if we can do better than just telling the RC to poll the AS.

There are a few options:
 - http long polling, this should "just work", so long as `continue.wait` is defined to allow it (we had quite extensive discussion over this for CIBA)
 - webhook, this could be something quite interesting to add in to the spec as it has many other uses.

**Comment by fimbault** [comment]
Interesting. We should probably map those technical possibilities to detailed use cases.

**Comment by jricher** [comment]
I believe both of these options are already available. As you say, long polling should just work, and we'd do well to pull in the lessons learned in CIBA.

The "callback" method allows for a "push" notification for post-interaction, which is functionally equivalent to a webhook.

The asynchronous authentication example is meant to be just that -- an example of how to accomplish this, not a required combination for that use case.

**Comment by yaronf** [comment]
If long polling "just works", please mention it in the draft as an option.

**Comment by fimbault** [comment]
There are still details to check out, like in CIBA long polling, if I remember well, there is a question of delay (like 30s). 
In practice there might be questions related to how to avoid DDoS. 

The difference I imagined in webhooks were more related to callbacks not specifically tied to a UI interact, but I'm not exactly sure which use cases that would cover.

**Comment by davidgtonge** [comment]
> The "callback" method allows for a "push" notification for post-interaction, which is functionally equivalent to a webhook.

Thanks @jricher I'd missed that.

**Comment by davidgtonge** [comment]
> The difference I imagined in webhooks were more related to callbacks not specifically tied to a UI interact, but I'm not exactly sure which use cases that would cover. Maybe notifications through partner apps, like slack etc.

Yep, there are many other uses for webhooks, however I think they may be outside the scope of the core spec. I think the core spec needs to be simplified where possible.

Re long polling, I do think it needs to be called out.
