### ISSUE TITLE
Names for Roles

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#32]
§1.2 Roles: Editor's note: 

The names for the roles are an area of ongoing
discussion within the working group, as is the appropriate precision
of what activities and expectations a particular role covers. In particular,
the AS might be formally decomposed into delegation components, that the
client talks to, and interaction components, that the user talks to. Several
alternative names have been proposed for different roles and components, 
including:

- Grant Server (for Authorization Server)
- Grant Client (for Resource Client)
- Operator (for Requesting Party)

See also #29

**Comment by fimbault** [comment]
Part of the terminology #29

**Comment by yaronf** [comment]
Process comment: I suggest to move the top note over to #29 and close this one as Duplicate.

**Comment by fimbault** [comment]
Closing as duplicate
