### ISSUE TITLE
Alignment with RAR

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#34]
§2.1.1 Requesting a Single Access Token: Editor's note: 

this will align with OAuth 2 RAR, but the details of exactly how it aligns are TBD. Since RAR needs to work in the confines of OAuth 2, RAR has to define how to interact with "scope", "resource", and other existing OAuth 2 mechanisms that don't exist in GNAP.

OAuth 2 RAR: https://tools.ietf.org/id/draft-ietf-oauth-rar-03.html

**Comment by fimbault** [comment]
This is informative mostly, will keep a look at RAR as it evolves.
