### ISSUE TITLE
End-user authentication towards the AS is considered to be "dangerous" !

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#342]
Section 12.9 (Exposure of End-user Credentials to Client Instance) states:

> Consequently, no interaction methods defined in the GNAP core require the end-user to enter their credentials, but it is technologically possible for an extension to be defined to carry such values.  **_Such an extension would be dangerous_** as it would allow rogue client software to directly collect, store, and replay the end-user’s credentials outside of any legitimate use within a GNAP request.

Such an incorrect conclusion is the consequence of a missing trust relationship.  

A key point is whether the end-user is trusting or not his client instance for not stealing his credentials and for displaying the correct information. 

Furthermore, "end-user authentication" is implicitly interpreted as being the use of a password (i.e. **_a single factor authentication_**).

GNAP should be targeted to be world-wide usable, including in Europe and the EU.  

As of December 31 st, 2020, the European Union (EU) is requiring that consumer electronic payments over € 50 ($ 60) require MFA (**_Multi-factor authentication_**). This requirement is defined as part of the Payments Services Directive (PSD2) that took effect in January 2018.

**Comment by aaronpk** [comment]
> Furthermore, "end-user authentication" is implicitly interpreted as being the use of a password (i.e. a single factor authentication).

Can you point to the current text that implies single factor authentication? This is not the correct interpretation, so we should make sure it is not interpreted that way.

Section 4 talks about authentication and interaction with the user https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-08.html#section-4

**Comment by Denisthemalice** [comment]
**_@aaronpk_** . Your question was:

> Can you point to the current text that implies single factor authentication? 

The text is:

> Consequently, no interaction methods defined in the GNAP core require the end-user to enter their credentials, but it is technologically possible for an extension to be defined to carry such values.  Such an extension would be dangerous as it would allow rogue client software to directly **_collect, store, and replay the end-user's credentials_** outside of any legitimate use within a GNAP request.

Such collection, storage and replay would be possible in the context of an Id and a password, but would not be possible in the context of a MFA (Multi-Factor Authentication). For example, if a one-time SMS code is received on the smartphone of the end-user and the end-user needs to enter that code. Replay is not possible.

Now, everybody his using a Laptop trusting, hoping (or praying) that it will not steal his passwords (_maybe with the exception of the OS software provider itself_). The key question is whether or not the end-user (entity A)  is trusting the Laptop or Desktop or Workstation or Smartphone he is using (entity B) for having an honest behavior (Behavior C).

You also pointed to Section 4.  Unfortunately, Section 4 is about the RO, i.e. not about the end-user when he is not also the RO.

My conclusion is that **_end-entity authentication towards the AS is NOT "dangerous"_**.

**Comment by jricher** [comment]
The "dangerous" attack is the end user authenticating through the client software by presenting their credentials to the client software and having the client software replay and present those credentials to the AS. This leaks security information to an untrusted piece of software, the client. Multifactor authentication technologies usually make this type of dangerous practice impossible as well by means of audience restriction, verifier impersonation resistance, and phishing resistance.

Section 4 is about getting the end user and RO involved in the security process.

**Comment by Denisthemalice** [comment]
I fear we don't understand each other because we do not share the same meaning for trust.
You are using the wording "untrusted piece of software, the client" which means nothing to me.

I believe that now that you know that a trust definition shall have three components:
Entity **_A_** trusts entity **_B_** for some kind of behavior **_C_**.

I believe that you authenticate to your mail server using an id (i.e. your email address or a part of it) and a password. 
If you don't trust your client, you should not use your client and hence you should stop sending or receiving emails.
Obviously, you send and receive emails and hence you trust your client to behave "honestly" ... until a virus has successfully attacked your client. Hence you have installed an anti-virus software to prevent that case.

As a conclusion: the end-user is trusting his client to behave honestly ... as long as he has not detected something wrong.

You also wrote:

> Multifactor authentication technologies usually make this type of dangerous practice impossible as well by means of audience restriction, verifier impersonation resistance, and phishing resistance.

However, the text is silent about MFA, so only schemes with Id and passwords are being considered.
