### ISSUE TITLE
The text is silent about how / when / if an AS is able to authenticate the end-user

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#343]
Section 12.11 (Processing of Client-Presented User Information) states:

> GNAP allows the client instance to present assertions and identifiers of the current user to the AS as part of the initial request.  This information should only ever be taken by the AS as a hint, since the AS has no way to tell if the represented person is present at the client software, without using an interaction mechanism.  This information does not guarantee the given user is there, but it does constitute a statement by the client software that the AS can take into account.

This highlights the fact that the information presented by the client about the end-user is only identifying the claimed end-user and **_by no way authenticating it._**

The following text is silent about how / when / if an AS is able to authenticate the end-user.

Later on the text continues with:

> In cases where the AS **_trusts the client software more completely_** due to policy or by previous approval of a given client instance, the AS can take this user information as a statement that the user is present and could issue access tokens and release subject information without interaction. 

What means **_more completely_** ?  **How may an AS **_trust the client software more completely_ ?** 

Note that the core protocol does not support any feature that is able to make the difference between a "trusted client instance" and 
an "untrusted client instance" from an AS point of view.

Anyway, such a case would not comply with the EU Payments Services Directive (PSD2) that took effect in January 2018.

**Comment by jricher** [comment]
The end user authenticates at the AS during the interaction and authorization process as discussed in section 4.

The means for trusting "more completely" is described in the rest of the sentence you quote above: "trusts the client software more completely due to policy or by previous approval of a given client instance".

**Comment by Denisthemalice** [comment]
The text of section 4 is about the RO, not about the end-user:

> authenticate **_the RO_**, through a local account or some other means such as federated login
validate **_the RO_** through presentation of claims, attributes, or other information
prompt **_the RO_** for consent for the requested delegation
describe to **_the RO_** what information is being released, to whom, and for what purpose
provide warnings to **_the RO_** about potential attacks or negative effects of allowing the information
allow **_the RO_** to modify the client instance's requested access, including limiting or expanding that access
provide **_the RO_** with artifacts such as receipts to facilitate an audit trail of authorizations
allow **_the RO_** to deny the requested delegation

About "more completely", my argument remains: The core protocol does not support any feature that is able to make the difference between a "trusted client instance" and an "untrusted client instance" from an AS point of view, or a "more completely" trusted client.
