### ISSUE TITLE
About the modified definition of a client in draft-08

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#344]
The sentence following the definition of a client has been modified into:

> The client is operated by the end-user or it runs autonomously on behalf of a resource owner.

The second part of this sentence (i.e. "or it runs autonomously on behalf of a resource owner") is not clearly understandable. 

There should be a scenario and further explanations within the document to explain the specific case of "a client running autonomously on behalf of a resource owner".

**Comment by jricher** [comment]
There are several sections and examples that talk about a client running autonomously, as has been pointed out before: 

https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-08.html#name-software-only-authorization

https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-08.html#example-no-user

These examples have been in the draft for a very long time, and the change to the definition text was added to align the formal definition with the intended functionality.
