### ISSUE TITLE
About the Note following the definition of a client

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#345]
The Note following the definition of a client is now:

>       Note: this specification differentiates between a specific
>       instance (the client instance, identified by its unique key) and
>       the software running the instance (the client software).  For some
>       kinds of client software, there could be many instances of that
>       software, each instance with a different key.

It is fine make the difference between a specific instance and the software running the instance (the client software). 

However, adding in parenthesis "(the client instance, identified by its unique key) leads to a specific architecture implementation that is not the consequence of the client definition which is: 

> "application that consumes resources from one or several RSs, possibly requiring access privileges from one or several ASs".

Associating a client instance with "its unique key" is not secure by design, since the private key **_value_** protection and the private key **_usage_** protection cannot be guaranteed: there is no mechanism or protocol described in the current draft that is able to guarantee the existence of these two protections. Hence, the architecture described in draft-08 has no means to prevent a collusion between two collaborating clients. 

A proposal able to address a collusion between two collaborating clients has been advertised on the mailing list, but up to now, has not been incorporated into the draft.

**Comment by jricher** [comment]
The need to protect keys representing a client instance is discussed at length in section 12.3: https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-08.html#name-protection-of-client-instan
