### ISSUE TITLE
The end-user consent has been forgotten, even in the case of a single AS

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#346]
In section 1.5 (Sequences), the first example indicates:

>    *  (1) The client instance determines what access is needed and which
>       AS to approach for access.  Note that for most situations, the
>       client instance is pre-configured with which AS to talk to and
>       which kinds of access it needs, but some more dynamic processes
>       are discussed in Section 9.1.

In both cases, the model considers only a single AS. 

Even in the "dynamic process", the returned information is still about a single AS, but even if there is a single AS, the end-user should have the choice to accept **_(or not_**) to get an access token from that AS. The end-user consent has been forgotten but still exists even if there is a single choice.

Obviously, an end-user consent also exists when a RS is trusting more that one AS 
(_which is a case that is not currently considered in draft-08_).

**Comment by jricher** [comment]
The end user consent is is captured during interaction with the AS, as discussed in section 4.
