### ISSUE TITLE
Why the requests from the client instance to the AS should (?) or shall (?) be signed ?

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#347]
About Section 12. Security Considerations (page 110)

Section 12.1 (TLS Protection in Transit) states:

> Even though requests from the client instance to the AS are signed, the signature method alone does not protect the request from interception by an attacker.

This has nothing to do with the title of this section which is "TLS Protection in Transit".

There is no justification of the reason(s) why the requests from the client instance to the AS should (?)  or shall (?) be signed.

**Comment by aaronpk** [comment]
This is describing why TLS protection in transit is still necessary even if requests from the client are signed.

The justification is at the top of section 12.1:

> to protect the contents of the request and response from manipulation and interception by an attacker

**Comment by Denisthemalice** [comment]
Your answer does not correspond to the question.

The question was "why the requests from the client instance to the AS should (?) or shall (?) be signed", knowing that TLS already protects the contents of requests and responses from manipulation and interception by an attacker.

**Comment by jricher** [comment]
@Denisthemalice the need for signatures in addition to TLS is the topic of section 12.2: https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-08.html#name-signing-requests-from-the-c

It is very common for different security consideration sections to focus on different aspects and different attacks. Sections 12.1 and 12.2 provide two perspectives on why two different security mechanisms are each needed.

**Comment by Denisthemalice** [comment]
The text in that section states:

> TLS is not targeted at tying multiple requests to each other over time.

Would you be able to elaborate ?

AFAIK, all the messages flowing through the same TLS connection are tied together.

**Comment by jricher** [comment]
@Denisthemalice Let's say you're using a browser, and you load one page, then another. Those pages are served with completely separate TLS connections. There is no transitive trust between those connections because the old connection's sockets are destroyed and the new connections sockets are created.

**Comment by Denisthemalice** [comment]
AFAIK, the connection's sockets are not destroyed as long as the same connection remains open.

For which reason should there be a separate TLS connection as long as those two pages belong to the same server ?

**Comment by jricher** [comment]
@Denisthemalice That is not how TLS works or what protections it provides.
