### ISSUE TITLE
About bearer access tokens

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#349]
Section 12.7 is about Bearer Access Tokens.

The text states:

> Bearer access tokens can be used by any party that has access to the token itself, without any additional information.

In the context of GNAP, bearer tokens are not defined (i.e. there is no definition of this wording). 

However, there exists a definition of the bearer flag which is the following:

> "bearer"  If this flag is included, the access token being requested is a bearer token.  If this flag is omitted, the access token is bound to the key used by the client instance in this request, or the key’s most recent rotation.

This makes the assumption that only two techniques are possible. 

Bearer access tokens do not include a key used by the client instance in its request.

At the moment, bearer tokens are considered to be insecure because they can be transmitted between clients and then be used easily by another client. However, it is possible to add in a bearer token a **_binding user identifier_** (buid) instead of a key which makes a third case.

So we should consider three cases:

- **_bearer access tokens_** that contain no binding element.
- **_key-bound access tokens_**, and
- **_user-identifier-bound access tokens_**.

**Comment by aaronpk** [comment]
As has been discussed before, adding a "binding user identifier" into a bearer token does not change it from being a bearer token. It is still a bearer token regardless of what information is associated with the bearer token.

Bearer tokens are [described in section 12.7](https://gnap-core-protocol-editors-draft.netlify.app/draft-ietf-gnap-core-protocol.html#section-12.7).

**Comment by Denisthemalice** [comment]
Section 12.7 states:

> It also means that any party that is able capture of the token value in storage or in transit is able to use the access token.

The issue #322 (Short term and long term RS user accounts) explains in details why this is not possible, as soon as the concepts 
of short term and long term RS user accounts are being used. 

If Bob got an access token that contains a "buid" field and transmits it to Alice, then Alice will not be able to use it on her own long term user account.

If Alice has opened a short term RS user account, she will not be able to use an access token issued to Bob that contains a "buid" field.

These properties are not supported by a bearer token, nor by a key-bound access token.

This explains why a third category of access tokens should be considered.

For the time-being, I have named it : **_user-identifier-bound access tokens_**.

**Comment by jricher** [comment]
@aaronpk is correct: the contents of the access token (or the claims they represent) are an orthogonal concern from the distinction between a bearer and key-bound access token. There is no "binding" to the user in what @Denisthemalice has proposed, as discussed on previous issues at length. Therefore, there is in fact no additional category as described here.

**Comment by Denisthemalice** [comment]
A "buid" is not a claim. It is a field that is separate from the claims.
 
With your argumentation, I understand that a bearer access token that would contain a "buid" field is still a bearer token. 

The problem is that such an access token would not comply with the text from Section 12.7 which states:

> It also means that any party that is able capture of the token value in storage or in transit is able to use the access token.

How would you solve such a contradiction ?

**Comment by jricher** [comment]
@Denisthemalice There is no contradiction. If Bob captures Alice's bearer token with Alice's `buid` claim, then Bob can use that token to access Alice's account.

**Comment by Denisthemalice** [comment]
@jricher . Section 12.1 states:

> TLS protects the response as well as the request, preventing an attacker from intercepting requested information as it is returned.

 Since TLS MUST be used, Bob cannot capture Alice's token unless Alice voluntarily transmits her access token to Bob.

**Comment by aaronpk** [comment]
There are other ways to capture a token. One common way TLS is not foolproof is in corporate networks that use a TLS proxy server to observe traffic on their network.

**Comment by jricher** [comment]
Tokens don't have to be captured in transit, they can also be exfiltrated from compromised software or platforms. It doesn't have to be willing participation of the user.

**Comment by Denisthemalice** [comment]
From a client point of view, the TLS proxy server is considered to be part of the RS. 
After the proxy, the traffic is using HTTP (i.e. no more HTTPs). 

So we would be in a case where a component that is supposed to protect the RS is in fact malicious: 
it sends back to Bob an access token received from Alice so that Bob can use it on Alice's account.  

Section 12.16.  MTLS Message Integrity states:
> The TTRP [ TLS-terminating reverse proxy ] has to be trusted ...

If that component is trusted, it will not send back to Bob an access token received from Alice.

Security is a matter of trust relationships. 
At the moment, these trust relationships are still left undefined in section 1.4.

**_@aaronpk_** : The TLS proxy server would need to be modified in order to take care of GNAP security requirements. 
                           So it would not simply be a TLS proxy server to observe traffic on the network.
