### ISSUE TITLE
Mapping resource references

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#35]
§2.1.2 Requesting Resources By Reference: Editor's note: 

>  Each string SHOULD correspond to a specific expanded object representation at the AS.

We could describe more about how the expansion would work. For example, expand into an object where the value of the "type" field is the value of the string. Or we could leave it open and flexible, since it's really up to the AS/RS to interpret.

**Comment by jricher** [comment]
Editors suggest closing as defining this would define internal behavior to the AS that does not affect interoperability.

**Comment by yaronf** [comment]
I see it as explanatory text. So instead of removing, maybe just change normative SHOULD to informative lower-case should.

**Comment by jricher** [comment]
The proposed resolution is not to remove the quoted text, or to change any text. The issue was suggesting that we could specify how the mapping would work at the AS, from string to a specific object. So for an example strawman:

```
resources: [ "foo" ]
```

would be defined, by GNAP core, as:

```
resources: [
{
   "type": "foo"
}
]
```

Or any specific expansion. The current text leaves this decision to an AS implementation, and the editors agreed that this was an internal detail of the AS and does not affect the interoperability of the protocol. If the working group wants to prescribe this kind of behavior as in-scope to the protocol, then we can do that with a concrete and specific proposal, but based on previous list discussions and the editors' discussions, there wasn't support for making that change.

Changing this to a non-normative statement or removing it entirely should be raised as separate issues if you think that's where it should go.

**Comment by aaronpk** [comment]
Closing this issue because there is no specific action to take. If the normative text needs to be changed (either to make it non normative or make it more strict), that can be raised in a new issue.
