### ISSUE TITLE
How to ensure that the end-user is present?

### ISSUE THREAD

**Issue by pq2** [ietf-wg-gnap/gnap-core-protocol#361]
[Section 2.5.2.1](https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-08.html#request-interact-callback-redirect) states that `the client instance MUST ensure the end-user is present on the request` when using the redirect interaction finish mode.

Perhaps this could be elaborated a bit further. I assume this means that if the redirect interaction start mode is used together with the redirect interaction finish mode, the client instance must validate session information as mentioned in [Appendix D.1](https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-08.html#name-redirect-based-user-interac), e.g. using a session identifier that is sent as a cookie. But how should the wording in Section 2.5.2.1 be interpreted if a different interaction start mode is used? When using the user code interaction start mode, for example, the interaction normally takes place on a different device, so cookies cannot be used for this validation.

**Comment by jricher** [comment]
Related to #22

**Comment by jricher** [comment]
This is more of a security consideration, so we will remove the normative requirements here and have a wider discussion about the different combinations and deployments and what these all mean for making sure the user is "there" in the different circumstances.
