### ISSUE TITLE
Trust relationships are still left undefined in GNAP draft-08

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#368]
Section 1.4 of draft-08 is supposed to be about “trust relationships”, but it is not. It is based on “Promise Theory” document (302 pages) where “ A promise is a stated intention ”. “ Each agent defines its own valuation function of promises given or received ”. 

On page 108 (!), there is a first attempt to define what Trust means:

      Proposal 1 (Trust). An agent’s expectation that a promise will be kept. 
      It may be assigned a value lying between 0 and 1, in the manner of a Bayesian probability.

Such an approach is confusing : it is mixing trust relationships with security threats.

In the IT community, trust is a binary condition (0 or 1): either you trust something or you don’t. **_It is not a Bayesian probability_**.
A trust relationship is rather simple and is composed of three parts : 

An entity A … is trusting an entity B … for some kind of behavior C.

…  being aware that some conditions “out of control” might happen

Section 1.4 of draft-08 is failing to indicate the trust relationships that may exist between:

   - Client instances and end-users,
   - End-users and ASs,
   - Client instances and ASs,

Trust relationships need to be clear and understandable. Without them, it will not be possible to demonstrate the security of the architecture.

In draft-08, the following questions have no answer:

    - How may a client instance be associated with an end-user ? This is left undefined. 
    - How may an AS be confident that a legitimate user is using a given client instance ? This is left undefined.

**Comment by fimbault** [comment]
Closing as already answered several times
