### ISSUE TITLE
A RS is currently only able to trust a single AS

### ISSUE THREAD

**Issue by Denisthemalice** [ietf-wg-gnap/gnap-core-protocol#372]
This limitation should be removed and can be removed. For details, see: draft-pinkas-gnap-core-protocol-00.txt

The Proposal for a Regulation amending Regulation (EU) No 910/2414 as regards establishing a framework for a European Digital Identity of 3 June 2021 should not be ignored. It paves the way for the use of multiple attribute servers.

If such limitation is not removed, it should be clearly advertised in the core draft.

**Comment by fimbault** [comment]
Closing as already answered several times
