### ISSUE TITLE
Allow a non-error response for a short redirect URL if other interaction modes are specified

### ISSUE THREAD

**Issue by aaronpk** [ietf-wg-gnap/gnap-core-protocol#375]
Currently the text says that if a client requests a short URL for the redirect and the AS can't fulfill it, an error should be returned. (I believe this was added in #53).

I think it makes sense to allow the AS to ignore the redirect mode if the client requested other methods as well, effectively treating it as a mode the AS doesn't support rather than an error.

**Comment by jricher** [comment]
The "short uri" mode was dropped a long time ago (at least in -03), so I'm not sure this is still relevant. What text are you seeing that calls for this error?

**Comment by aaronpk** [comment]
It seems I managed to find an old version of the spec, the current version doesn't have this error condition.
