### ISSUE TITLE
safe URL description

### ISSUE THREAD

**Issue by fimbault** [ietf-wg-gnap/gnap-core-protocol#376]
in 4.2.3.1 and 4.2.3.2, for base64 encoded URLs with no padding (+ by the way, we should explain what we mean by no padding and URL safe)

**Comment by jricher** [comment]
Base64 URL-safe encoding, with and without padding, is defined in RFC4648.

URLsafe: https://datatracker.ietf.org/doc/html/rfc4648#section-5

Optional padding: https://datatracker.ietf.org/doc/html/rfc4648#section-3.2
