### ISSUE TITLE
Token flags

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#39]
§2.1.4 Signaling Token Behavior: Editor's note: 

While these reference values are "reserved", the ultimate decider for what a reference means is the AS, which means an AS could arguably decide that one of these values means something else. Also, this kind of reservation potentially steps on API namespaces, which OAuth 2 is careful not to do but common extensions like OIDC do with their own scope definitions. However, in OIDC, several "scope" values have behavior similar to what's defined here, particularly "openid" turns on ID tokens in the response and "offline_access" signals for the return of a refresh token, and these can be used outside of OpenID Connect itself. However, to keep these flags out of the general API namespace, we could use a different syntax for sending them. In particular, they could be defined under a GNAP-specific "type" object, where all the flags are fields on the object.

```
resources: [
    {
        type: "gnap-flags",
        flag1: true,
        flag2: false,
        flag3: true ...
    },
    "reference1",
    "scope2", ...
]
```

Alternatively, all the flags could be sent in an array separate from the rest of the request.

```
resources: [
    "reference1",
    "scope2",
    ["flag1", "flag2", "flag3"] ...
]
```

This whole thing might also belong in an extension, as it's advanced behavior signaling for very specific cases. However, it seems other extensions would be likely to extend this kind of thing, like OIDC did with "offline_access".

**Comment by aaronpk** [comment]
This potential namespace conflict issue stood out to me as well and I think it would be better to solve earlier than later. Especially if this kind of thing does end up in an extension, it makes sense to have a way for extensions to define additional flags in a way that won’t conflict with other defined resource references.
