### ISSUE TITLE
Name the first sequence

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#392]
Sec. 1.5 (Sequences) would be clearer if we named the top sequence - all other sequences have been named. Maybe "main authorization flow"?

**Comment by fimbault** [comment]
The sequences have not been names per say, they just happen to be related to a subtitle. 

We could of course create a new subsection, but the idea was to place this sequence above the others.

**Comment by yaronf** [comment]
This is purely editorial. Naming it would make it easier to refer to this sequence.
