### ISSUE TITLE
Access rights by reference

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#407]
We say: 

> Access rights MAY be communicated as a string known to the AS or RS representing the access being requested. Each string SHOULD correspond to a specific expanded object representation at the AS.

But then we give examples like "some other thing" that clearly do not correspond to anything. We also don't specify any kind of semantics, such as if I request the reference string, I might get back the expanded access right representation.

I suggest to remove or weaken that sentence: 

> Each string may or may not correspond to a specific expanded object representation at the AS.

**Comment by jricher** [comment]
I don't see a reason for it not being a SHOULD -- it provides guidance to API developers that the strings a short-hand for the expanded objects. And since it's only a SHOULD, the AS is still free to treat it differently.

**Comment by yaronf** [comment]
No, this would be a MAY. With a SHOULD, you're supposed to have a good, documented reason to do something else.

Quoting the original,

> SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

If we keep the SHOULD, our examples in the text should reflect that.

**Comment by jricher** [comment]
@yaronf I've proposed a change to the text in question in #423.

Also, please note that the example string of `"some other thing"` is intended to be an actual value, with spaces and all. If it's not clear that this is a real and valid value in this context, please suggest an alternative that might fit here. We don't want people to assume that it has the same restrictions as OAuth scopes (which can't have spaces).
