### ISSUE TITLE
grant_request_endpoint - URL matching?

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#408]
When we define this value in the Discovery section, we say:

> This URL MUST match the URL the client instance used to make the discovery request.

I don't understand this sentence. Clearly the grant request and the discovery request URLs are not the same.

**Comment by jricher** [comment]
No, the discovery endpoint and the grant endpoint are the same -- it's the difference of doing an OPTIONS instead of a POST on the endpoint. That's why they have to match.

**Comment by yaronf** [comment]
Got it. I still don't understand the benefit in having this constraint. I can imagine cases where we want to keep the discovery URL constant while changing the grant request URL, e.g. to support API changes.

**Comment by jricher** [comment]
@yaronf because changing out the token endpoint in an untrusted way is behind several AS-mix-up attacks in the OAuth space, and this is one clear way to avoid that entire category.

**Comment by yaronf** [comment]
OK, makes sense. Personally I wouldn't include a value that's already known to the client in a response but that's more of a cosmetic concern and YMMV.
