### ISSUE TITLE
RS-first discovery: security aspects

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#409]
This discovery method is great for usability but worrying from a security POV. The RS is telling the Client to create a request to an arbitrary AS using an arbitrary access specification and the Client's credentials. The Client doesn't have any way to understand, validate or filter anything in the RS's response, so it cannot protect itself.

By the way, shouldn't we use a semicolon before the `access` parameter?

```
WWW-Authenticate: \
  GNAP as_uri=https://server.example/tx;access=FWWIKYBQ6U56NL1
```

A possible workaround is to add something analogous to a `Referrer` parameter to the AS access request containing the RS address, require the Client to include it, and require that the AS validate that the request is indeed to that RS.

**Comment by jricher** [comment]
In this scenario the client is explicitly looking to the RS to provide a pointer to which AS to talk to. In most cases this is pre-configured (the client knows which AS protects which RS). In some cases this will be communicated at runtime, using this mechanism. There are both security and privacy ramifications for this choice, which we've covered at least some of in the current text. I'm sure this can be expanded.

**Comment by agropper** [comment]
GNAP is a delegation protocol that enables separation of control from
processing with obvious advantages to all three parties (subject,
controller, processor). The RS is typically a processor. The choice of AS
as delegated controller SHOUlD lie with the subject in order to better
represent their interest.

This perspective is, of course, not absolute but it the should makes it the
preferred path.

**Comment by yaronf** [comment]
@jricher I don't see anything explicit about this call. The client just makes a normal-but-unauthenticated call to the RS, with no special indication that it's doing discovery. In fact a malicious RS can redirect the client anyway, even if the client is in fact authenticated.

And I don't see anything in the text about the threat vector of a malicious RS.

Please also respond to my syntactic comment above.
