### ISSUE TITLE
Discuss ways to find the grant endpoint

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#411]
The discovery process defined in GNAP details how to get information about the AS once you know the grant endpoint and can talk directly to it. We do not cover how to get the grant endpoint, except in the one case of it being provided by the RS at runtime in a response. The core document should at least discuss this gap as intentional, and an extension specification (or several) could be written to fill this gap in different circumstances.

**Comment by fimbault** [comment]
Maybe we should list a few other cases, that would require knowledge of the grand enpoint
