### ISSUE TITLE
Guidance on bridging OAuth RS to GNAP

### ISSUE THREAD

**Issue by agropper** [ietf-wg-gnap/gnap-core-protocol#422]
OAuth is de-facto mandated for RS APIs in healthcare and other application domains. In previous work we demonstrated a patient-controlled bridge between OAuth-secured health records (stored in US-standard hospital records as well as US-Medicare insurance claims) and a UMA2 patient-controlled authorization server and a UMA-secured health record. Regulatory mandates for a patient's right of access are a common basis for client registration in institutional OAuth systems.

Consider a bridge between the Alice-to-Alice and Alice-to-Bob use-cases. Would it be a good idea for GNAP to include non-normative guidance on how Alice's GNAP AS can also act as Alice's OAuth Client to mediate or proxy a resource request by Bob?

**Comment by agropper** [comment]
There are two clients in this use-case. Alice has a mandated right to use
her client, any client, to talk to the RS. Alice has no control over Bob’s
client and, in many cases such as an employer’s IT system, neither does
Bob.

It’s not obvious how GNAP should be used in this case.

**Comment by jricher** [comment]
Discussed on editors' call, it would be helpful to the discussion if you could provide actual text that would address this use case.

**Comment by jricher** [comment]
No text has been proposed for this use case, closing the issue.
