### ISSUE TITLE
User information request items

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#43]
§2.2 Requesting User Information: Editor's note: 

We're potentially conflating these two types in the same structure (`sub_ids` and `assertions` are both in `subject`), so perhaps these should be split. There's also a difference between user information and authentication event information.

**Comment by fimbault** [comment]
Question: do we need to manage assertions about someone else (like: I'm the doctor for this patient)? or limited to same user?

**Comment by yaronf** [comment]
This issue is tagged next to the following cryptic sentence:

> Note: the "formats" and "assertions" request fields are independent of each other, and a returned assertion MAY use a different subject identifier.

What do we mean by "a different subject identifier"?

**Comment by jricher** [comment]
You could get back something like this as a subject identifier:

```
format: email,
email: foo@example.com
```

But the assertion could be an ID Token with:

```
iss: idp.example.com,
sub: 87yhjio9876tg
```

Basically the assertions and identifiers are all talking about the same PERSON but they don't have to all do so in the same WAY.

**Comment by yaronf** [comment]
So please reword the sentence to clarify. E.g.:

>Note: the "formats" and "assertions" request fields are independent of each other, and a returned assertion MAY use a different subject identifier than specified in the request, as long as it refers to the same person.

**Comment by fimbault** [comment]
yes, that's clearer. I'll make a PR
