### ISSUE TITLE
Meaning of “delegated access” and guidance on data minimization for privacy

### ISSUE THREAD

**Issue by agropper** [ietf-wg-gnap/gnap-core-protocol#431]
The description #427 evolving around the state diagram is very clear and helpful, partly because it's focused on the AS as a semi-autonomous or policy-driven delegate. However, we should acknowledge that the End User, RO and Client as well as the AS are delegates themselves and have distinct privacy interests. For example:

- Is the RS a delegate of the RO? Probably.
- Is the AS a delegate of the RS? Maybe.
- Is the Client a delegate of the End User? Almost by definition, yes.
- Is the End User separately represented by both a Client and a secure Authenticator? Ideally.

Because, GNAP tries to steer the RO and other End Users through the same AS we risk confusing or conflating the privacy interests of the various actors. 

For example:
- As a RO, I want to minimize the request data an AS can see by having requests go to a delegate that I choose. How do I do that?
- As an End User, I want to minimize the request data shared with the AS by having the opportunity to delegate and attenuate the authorization I receive from the AS.
- As a system architect, I want to have non-repudiate attribution to any and all End Users even when the Client acting on behalf of an End User is a cloud server separate from their hardware-secure mobile authenticator.
- As an RO, I want to choose my RS separately from my AS as, for example in UK Open Banking.

I respect that much of this can be dismissed as out-of-scope for GNAP, but “delegated access” begs the question of what is the delegate of the End User as a party with overarching privacy and security interests.

**Comment by jricher** [comment]
GNAP deals with delegation to the client instance. This right is delegated by the RO. The end user uses the client instance to exercise this delegated access. In my view, all other forms of handling delegation explicitly are out of scope for GNAP, but GNAP can accommodate them.

**Comment by fimbault** [comment]
When looking at your PR, i get to the same conclusion as @jricher (see details in the related comments)

**Comment by agropper** [comment]
For clarity, please, the client that @jricher is referring to is the client as delegate of the RO. When the end user is using a different client, that client is not a delegate of the RO, depending on how we define “delegate”. It would be helpful if the editors could answer the scenario of this issue more directly if possible.

**Comment by fimbault** [comment]
@agropper I don't think we have an ambiguity here. 

"GNAP tries to steer the RO and other End Users through the same AS" : no, this use case is briefly mentioned in section 4 but is not covered by the core spec as such.

**Comment by fimbault** [comment]
There's nothing in the quote that says that the RO isn't able to chose its AS or that it is required to share a policy. 
Even if it's obviously preferable to have the RO exercice its full agency, I believe it really depends on the situation though. For instance the project I currently work for is a national health system, it's centralised and so the RO doesn't have much choice (well, the only choice is to use or not the plateform).

Plus I would note that in principle, people today are able to chose whichever service (google, microsoft, facebook, etc.) they wish to use. No one forces them to do that. And yet here we are. 
So this seems like a very subtle issue to me, and not one that any protocol can fix easily. 

That said, GNAP tries to take as much care as it seems possible to do. I still believe this would be better suited for the RS draft, though.

**Comment by agropper** [comment]
This issue and the [human rights considerations PR](https://github.com/ietf-wg-gnap/gnap-core-protocol/pull/434) are both about how much GNAP can or should do normatively. It's pretty clear that without a normative component, platform centralization will continue and regulators will continue to be captured for lack of appropriate technical options. 

Whether the issue is dealt with in core or the RS draft seems less important than that it be normative for anything labeled GNAP as a delegated authorization protocol.

Because this is a subtle issue, I suggest we reach out to the IRTF [HRPC](https://datatracker.ietf.org/rg/hrpc/documents/) for their input. Do we know how to do that?

**Comment by fimbault** [comment]
I suggest we transfer this issue to the RS draft, I'll propose a PR based on your input.
Then we can try to get feedback from interested parties, such as HRPC. 
Would that be fine ?

**Comment by agropper** [comment]
Yes. That should work.

**Comment by fimbault** [comment]
Moving this issue to RS
