### ISSUE TITLE
AS Validation of RC-presented assertions

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#49]
§2.4 Identifying the User: Editor's note:

> Assertions SHOULD be validated by the AS. 

Is this a MUST? Assertion validation is extremely specific to the kind of assertion in place, what other guidance and requirements can we put in place here?

**Comment by fimbault** [comment]
See previous phrase "Subject identifiers are hints to the AS in determining the RO and MUST NOT be taken as declarative statements". If so, there's no reason to that as a MUST.

Seems we're talking about a very specific assertion here (presence of RO). We should make an explicit section regarding that topic. Plus there are cases where this presence might not be needed at all (automatic rule engine).

**Comment by fimbault** [comment]
Move the security consideration next to SHOULD
