### ISSUE TITLE
User identification items

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#50]
§2.4: Identifying the User: Editor's note:

We're potentially conflating identification (sub_ids) and provable presence (assertions and a trusted reference handle) in the same structure, so perhaps these should be split. The security parameters are pretty different here.

See also #43

**Comment by fimbault** [comment]
Yes see #49 too, this is currently confusing (depends on what we expect assertions to be -> here presence of the RO)

**Comment by jmandel** [comment]
Also a quick note that the definition of these fields currently pertains to the end user, but all the guidance about their use talks about the RO as the subject of these fields (which I don't think is necessarily intended as the only case? Can't the subject/user here be the requesting party?)

**Comment by fimbault** [comment]
That's currently the intended behaviour, we provide the more general case in the intro of section 4 but the core protocol handles only this case user = RO
