### ISSUE TITLE
IESG frquently asked review questions

### ISSUE THREAD

**Issue by yaronf** [ietf-wg-gnap/gnap-core-protocol#507]
Can you please go through the following list and confirm that everything is covered appropriately.

Copied from https://wiki.ietf.org/group/iesg/ExpertTopics :

- Threat modeling: what needs to be protected and in what environment(s)?
- Trusted and untrusted parties
- Terminology relating to security concepts
- Matching threats to threat mitigation
- Use of TLS and IPsec, especially parameter recommendations and peer authentication procedures
- Creating new cryptographic approaches (spoiler: don't)
- Randomness
- Documents describing YANG modules have a specific security considerations template
- Assumptions that implementations won't maliciously ignore protocol requirements
- Agility of cryptographic algorithms
- "This document introduces no new security considerations" is nearly always wrong (though the new considerations may not be very interesting)

**Comment by jricher** [comment]
I believe that all the points on this list have been covered. @fimbault ?

**Comment by fimbault** [comment]
Yes indeed. @yaronf if that helps I can retrieve issues and PR related to each item in the list. Please let me know.

**Comment by yaronf** [comment]
> Yes indeed. @yaronf if that helps I can retrieve issues and PR related to each item in the list. Please let me know.

No need, I just needed your confirmation. Closing the issue.
