### ISSUE TITLE
Create more examples of interaction modes

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#52]
§2.5 Interacting with the User: Editor's note: 

There need to be more examples (Appendix C) that knit together the interaction modes into common flows, like an authz-code equivalent. But it's important for the protocol design that these are separate pieces to allow such knitting to take place.

**Comment by fimbault** [comment]
There are actually more examples that have been documented (sequences and appendix), seems enough for now.
