### ISSUE TITLE
Question about user code URI

### ISSUE THREAD

**Issue by michielbdejong** [ietf-wg-gnap/gnap-core-protocol#545]
> The user
   code URI MUST be reachable from the end user's browser, though the
   URI is usually be opened on a separate device from the client
   instance itself. 

I think this should be "is usually **_to_** be opened" or "is usually opened", not "is usually be opened"?

> The URI MUST be accessible from an HTTP GET request
   and MUST be protected by HTTPS, be hosted on a server local to the
   RO's browser ("localhost"), or use an application-specific URI scheme
   that is loaded on the end user's device.

If I try to put brackets into this sentence I get:
```
MUST(accessible from an HTTP GET request) AND MUST(
  (protected by HTTPS) OR
  (hosted on a local server) OR
  (using an application-specific URI scheme)
)
```

But the combination of `(accessible from an HTTP GET request)` with `(using an application-specific URI scheme)` is impossible, right?

Maybe what was intended is:
```
MUST(
  ((accessible from an HTTP GET request) AND (protected by HTTPS)) OR
  (hosted on a local server) OR
  (using an application-specific URI scheme)
)
```

**Comment by jricher** [comment]
First, please note that the document is with the RFC editor and no changes are being made through this repository.

Second, that sentence is meant to provide three options:

The URI MUST:

- be accessible from an HTTP GET request and either: 
    - be protected by HTTPS; or
    - be hosted on a server local to the RO's browser
- use an application-specific URI scheme

In other words, if it's a remote URI, it has to be HTTPS and has to be usable with GET (ie, doesn't require POST). If it's a local URI, it has to be accessible with GET over HTTP but doesn't need to be HTTPS. If it's a non-HTTP application-specific scheme then the HTTP semantics (GET) don't apply.

**Comment by michielbdejong** [comment]
Thanks for your reply!

Yes, that makes sense and that's also what I thought it was probably meant to say.

I'll close this issue and my PRs then. I'll keep a reference of the typos I found in case I maybe find another way to contribute them at some later point.

**Comment by jricher** [comment]
Thanks, when the document come back for author review I'll scan through these typos in case any of them don't get picked up by the RFC Editor.
