### ISSUE TITLE
Hash algorithm identifiers

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#56]
§2.5.3 Receive a Callback After Interaction: Editor's note: 

This should be expandable via a registry of cryptographic options, and it would be good if we didn't define our own identifiers here. 

§4.4.3 Calculating the interaction hash: Editor's note:

These hash algorithms should be pluggable, and ideally we shouldn't redefine yet another crypto registry for this purpose, but I'm not convinced an appropriate one already exists. Furthermore, we should be following best practices here whether it's a plain hash, a keyed MAC, an HMAC, or some other form of cryptographic function. I'm not sure what the defaults and options ought to be, but SHA512 and SHA3 were picked based on what was available to early developers.

**Comment by aaronpk** [comment]
This is probably the right registry to reference:

https://www.iana.org/assignments/named-information/named-information.xhtml
