### ISSUE TITLE
Push-based post-interaction hook

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#60]
§2.5.3.2 Receive an HTTP Direct Callback: Editor's note: 

This post-interaction method can be used in advanced use cases like asynchronous authorization, or simply to signal the client that it should move to the next part of the protocol, even when there is no user present at the client. As such it can feel a little odd being inside the "interact" block of the protocol, but it does align with the redirect-based "callback" method and it seems they really should be mutually-exclusive. Additionally, should there be a method for simply pushing the updated response directly to the client, instead?

**Comment by davidgtonge** [comment]
This is a tricky one. I agree that the fact they should be mutually exclusive makes putting them both under the `callback` section make sense. 

Typically a redirect based interaction would occur in a short time window. Whereas a push based interaction has no such limitation.  Is this something that should be specified rather? 

In CIBA we added the `requested_expiry` option which allows the RC to signal the time window where it requires the callback. This is important as some interactions need to happen while a user is present (even if no redirect is involved), whereas others have no time pressure.

**Comment by jricher** [comment]
This has been obsoleted by the move to the interaction `finish` structure.
