### ISSUE TITLE
Provide guidance for defining new interactions

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#61]
§2.5.6 Extending Interaction Modes: Editor's note: 

We should have guidance in here about how to define other interaction modes. There's already interest in defining message-based protocols like DIDCOMM and challenge-response protocols like FIDO, for example.

**Comment by fimbault** [comment]
Closing this sub-issue (as there are several issues with similar concerns) and enclosing it into a more general issue
