### ISSUE TITLE
Referencing an existing grant request

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#62]
§2.7 Referencing an Existing Grant Request: Editor's note: 

This basic capability is to allow for both step-up authorization and downscoped authorization, but by explicitly creating a new request and not modifying an existing one. What's the best guidance for how an AS should process this? What are the use cases that help differentiate this from modification of an existing request?

**Comment by aaronpk** [comment]
This section could also benefit from some explanation of use cases for this, describing step-up and downscoped authorization.

**Comment by fimbault** [comment]
The text is currently not very clear. "The AS MUST dereference the grant associated with the reference and process this request in the context of the referenced one. The AS MUST NOT alter the existing grant associated with the reference." We could explain the use cases as suggested in this issue, and explain that it's an immutable reference (yes, I'm doing too much rust ;-)).

Supposing we have that ref available, I'm not sure how the AS is supposed to handle that. Does it mean: "ok you're already vetted", so I just need to check the diff but I can skip what's the same?

**Comment by jricher** [comment]
this section was removed; discussion of grant identifiers is subsumed by #146 and discussion of grant APIs
