### ISSUE TITLE
Splitting the "claims" request

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#63]
§2.8 Requesting OpenID Connect Claims: Editor's note: 

In order to use the "claims" parameter as defined in OIDC, we have to violate the principle of orthogonality in Section 2.9. An alternative approach would be to split up the portions of the claims request, so that "id_token" claims would go into the "subject" field and "userinfo" claims would go into the "resources" request, but this violates the original field definition from OIDC and gets into the territory of defining an identity schema request. This approach would also invalidate extensions to the "claims" standard as each "target" would need to have its own separate mapping to some part of the GNAP protocol.

**Comment by fimbault** [comment]
This is informational, should follow the fate of #64
