### ISSUE TITLE
Including OpenID Connect claims

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#64]
§2.8 Requesting OpenID Connect Claims: Editor's note: 

I'm not a fan of GNAP defining how OIDC would work at all and would rather that work be done by the OIDF in an extension. However, I think it is important for discussion to see this kind of thing in context with the rest of the protocol, for now. In the future, I would anticipate this would be defined by the OIDF as a relatively small but robust identity layer on top of GNAP.

**Comment by aaronpk** [comment]
Is it worth adding a note in this section of the document saying that this section may be removed before final publication?

**Comment by jricher** [comment]
Editors recommend removing this section from the core document to allow for future extension and compatibility layer with OpenID Connect.
