### ISSUE TITLE
Continuation API artifact structure

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#67]
§3.1 Request Continuation: Editor's note: 

The AS can use the optional "access_token" as a credential for the client to manage the grant request itself over time. This is in parallel with access token management as well as RS access in general. If the AS uses the access token, the continuation URL can be static, and potentially even the same as the initial request URL. If the AS does not use an access token here, it needs to use unique URLs in its response and bind the client's key to requests to those URLs - or potentially only allow one request per client at a time. The optionality adds a layer of complexity, but the client behavior is deterministic in all possible cases and it re-uses existing functions and structures instead of inventing something special just to talk to the AS. The optional access token represents a design compromise, but the working group can decide to either require the access token on all requests or to remove the access token functionality and require the security of the continuation requests be based on unique URLs.

**Comment by fimbault** [comment]
From yesterday's discussion at IETF109, it seemed we agreed that it would be best to have only one way to do the continuation. 

I personally would be in favor of having a mandatory access token (not a bearer token, needs to prove key possession), and a simple uri. As @aaronpk remarked, "https://server.example.com/continue/80UPRY5NM33OMUKMKSKU" is effectively an access token in a URL, also known as a capability URL, which the w3c has a whole document about the pros and cons of: https://www.w3.org/TR/capability-urls/#recommendations. 

I also note the proposal to rename "access_token" into "access". 

```
"continue": {
   "access": {
      "value": "80UPRY5NM33OMUKMKSKU",
      "key": true
   },
   "uri": "https://server.example.com/continue",
   "wait": 60
}  
```

**Comment by yaronf** [comment]
@fimbault No, my proposal to rename `access_token` to `access` referred to two of the proposals to address #40, not to the example you are quoting. There we bundle a LOT more into a structure called `access_token`. Slides 32-33 of the deck.

**Comment by fimbault** [comment]
my bad, makes sense. I crossed the related line in the previous comment, and updated the json.
note for the future: if we can avoid going back and forth in the presentation, will avoid such misunderstandings ;-)

**Comment by jricher** [comment]
Part of the confusion here is that we're talking about changing the format of what's currently `access_token` in response messages. That construct gets used in both the continuation protocol (here) and in the access tokens for RS's. The parallelism is deliberate, so if we change it in one place it'll change in both.

I'm in favor of both requiring the access token for the continuation API and in renaming the structure to `access`, but these are separate issues.

**Comment by dickhardt** [comment]
"https://server.example.com/continue/80UPRY5NM33OMUKMKSKU" is an identifier 
just as "https://server.example.com/grant/87h34gsU5Snj9019" is an identifier

It is not a capability URL, as there is NO authentication with capability URLs. In GNAP, the API calls are all authenticated by the client proving possession of its key.

Per my email to the list, what we are calling an access token is more like a cookie as it is maintaining state. How it is set, where it can be presented, are unlike other access tokens -- calling it an access token dilutes the meaning of access tokens and is confusing.

**Comment by fimbault** [comment]
It's not a cookie either. The goal is not to maintain state, it's only to execute the next transition. And by the way it's lucky it isn't, we don't want to enter into the legal territory of cookies. 
That's the limit of analogies (neither a capability nor a cookie). 

If I summarize we have the following issues:
- putting the token directly in the url exposes to potential unexpected url logging from proxies (we don't want that) 
- setting the token aside is the alternative, but the difference with a standard access token (as used by RS) might be confusing to implementers (I agree there is a little risk here). That difference is currently expressed by the "key" boolean parameter, which could easily be overlooked. 

If we want to stress the difference, there are a few options:
- call it differently altogether (like "continue token"). We'd loose the parallelism that Justin was talking about though (which is nice if we can find a way to avoid the confusion at minor cost) 
- add a "type" within the json of the access token. But then we need to deal with mutual exclusivity with the key field. Not a good idea.
- change the key field to a name that is more meaningful, like "requires_key_authentication". I believes it conveys the meaning better. 

With the last option we could have  

"continue": {
   "access_token": {
      "value": "80UPRY5NM33OMUKMKSKU",
      "requires_key_authN": true
   },
   "uri": "https://server.example.com/continue",
   "wait": 60
}

**Comment by jricher** [comment]
The `key` parameter is not different from the standard access token response, though -- it's a required field for all access tokens, no matter which API they call (whether it's within the AS like the continuation API or an OpenID UserInfo Endpoint, or a separate RS alltogether). 

https://www.ietf.org/archive/id/draft-ietf-gnap-core-protocol-02.html#name-single-access-token

The only difference here is that the `key` field is currently restricted a specific required value because we want to limit what we expect the client to be able to do when calling the continuation API. The boolean value of `true` signals that the token is bound to the same key the client presented during its initial request. This means that the client needs to continue to present that key along with the access token for the continuation calls. I would argue (as others have) that this ought to be the default for :all: access tokens issued to the client within GNAP. We could relax this restriction, but it would mean that we'd end up with a potentially more complex space for a client to deal with when an AS binds to a different key or proofing mechanism for continuation. Plus, I think we all agree that a bearer token for continuation is a non-starter.

**Comment by fimbault** [comment]
Yes if we make key verification mandatory, it removes the issue altogether, improves the security, and I see no potential confusion for the implementer.
It might come as a challenge where bearer tokens are used today (for APIs). Not hard to implement, but any change like that takes time to disseminate within the ecosystem.

**Comment by jricher** [comment]
This is an interesting approach. I'm in favor of the proposed default behavior of binding to the client's key, but I'm not sure I'm sold on default values when a field is absent, like this. In the current spec, the only way to get a bearer token is to set `"key": false` in the token response. Since `key` is mandatory there is technically no ambiguity about the nature of a token since there's no "default" value if it's not present, it's an error. 

An older version of the XYZ draft had something similar, with a `"proof": "bearer"` field alongside a separate `key` field. The problem came from the situation of having a bearer flag alongside a key. That was an error condition that needed to be checked by the client now. With the current draft, that error is impossible at a syntax level, which I think is a benefit for client implementors.

**Comment by jricher** [comment]
To expand a bit: what I'm saying is that the semantics of key binding need to be very clear for the token. A client implementor should never overlook the `key` value in the current access token structure since it says exactly how the token is bound to outgoing requests.

**Comment by fimbault** [comment]
I agree with that. I think we're on similar lines of thought here. 
One could argue however that having a true/false flag makes it possible to overlook the field (hence why I suggested that in the case of continuation, it's not even present; or if we want to make it explicit, the only valid json contains "key":true).

**Comment by jricher** [comment]
We could combine the concepts, and say that if the `key` field is not present, its value is `true`.

**Comment by jricher** [comment]
Thinking about this for half a second more, I think we need to refactor out the key presentation and its semantics from where it is in the spec right now, since it isn't just about the client presenting a key: #130

**Comment by aaronpk** [comment]
tbh `"key": true` doesn't tell me much about what that is or why I need it. I'd be in favor of naming it something more specific.

**Comment by fimbault** [comment]
Since we had a lengthy discussion on the rationale for the change, I copy paste it here

 - The access token pattern has a lot of benefits, otherwise we wouldn’t have an entire OAuth ecosystem based on it
 - Magic URIs have a lot of drawbacks which are well understood; while they can be mitigated, they can also be avoided
 - Continuation is an API, and treating it like the other kinds of API the client would call makes sense
 - Calling this by a special name, like “grant access token” or “continuation access token” is fine, but it should function like any other access token
 - The heavy lift for clients is on protecting the message cryptographically, which they need to do anyway

From https://mailarchive.ietf.org/arch/msg/txauth/YFAgBmCWXgTuESfj-0iDCOg39xc/
