### ISSUE TITLE
Uniqueness of Token Management URIs

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#70]
§3.2.2 Multiple Access Tokens: Editor's note:

> If management is allowed, each access token SHOULD have different management URIs.

Do we need to specify that the management URIs are different if we require the token to be presented?

**Comment by fimbault** [comment]
I think we can actually remove this requirement, or make this a MAY; as long as the URI is required in the response, it's up to the AS how to manage things; we do want to say that it can't contain the access token value itself
