### ISSUE TITLE
Privacy considerations of returned user information

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#74]
§3.4 Returning User Information: Editor's note: 

Privacy considerations are needed around returning identifiers.

This will need substantial privacy considerations, as this is releasing information about the current user that could be tied to other information at the RC or elsewhere. To facilitate this, should we have another form of identifier that's a globally unique identifier of some form? DIDs could facilitate that kind of namespace.

**Comment by fimbault** [comment]
We create a global issue for privacy consideration. #74 will be part of that global effort, but closing right now and referencing it into the new global issue.
