### ISSUE TITLE
Dynamic RC instance registration

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#77]
§3.5 Returning Dynamically-bound Reference Handles: Editor's note: 

The ability to dynamically return reference handles allows for an inline version of dynamic registration without needing to go through a discrete registration step, for clients where that makes sense. Currently this is entirely up to the AS to decide when to issue these, but maybe the client should signal that it can receive these handles as part of the request? The new "token flags" construct in Section 2.1.4 almost gets at that, but for a different part of the request structure. Since the client is the component that will know if it's in a position to make use of such reference handles in the future (like a mobile app) or if it's just going to evaporate at the end of a session (like an SPA). Ultimately we need to deal with a range of dynamism, not just the "pre-registered" vs. "non-registered" use cases that OAuth forces us in to.

**Comment by aaronpk** [comment]
I would assume the client would always be expected to handle these, not optional. It's already a SHOULD in fact.
