### ISSUE TITLE
Error responses

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#79]
§3.5 Error Response: Editor's note: 

I think we will need a more robust error mechanism, and we need to be more clear about what error states are allowed in what circumstances. Additionally, is the "error" parameter exclusive with others in the return?

**Comment by adeinega** [comment]
As a starting point, I would suggest adding these sentences

The error code parameter MUST be required and its value SHOULD be limited to ASCII characters.

The error code `invalid_request` indicates that a request is malformed.

The AS MUST return an HTTP 401 (Unauthorized) status code to indicate that it can't identify a client instance (the error code can be `invalid_client`).

The AS MUST return an HTTP 401 (Unauthorized) status code to indicate that it can't authenticate a client instance (the error code can be `invalid_client`).

The AS MAY uncover additional information about the cause of the error when it can authenticate a client instance (the error code can be `invalid_grant`, `invalid_interaction`, and so on).

**Comment by jricher** [comment]
Addressed by #385, still need error codes for things like token management.

**Comment by adrianhopebailie** [comment]
The type of the of the error property in a response is currently ambiguous.
In section 3 it is defined as an `object` and in section 3.6 it is defined as a `string`.

**Comment by jricher** [comment]
@adrianhopebailie thanks for catching that -- looks like both "error" and "error_description" should be added to the list of parameters. I think the intent might have been for the value of "error" to be an object with "error_code" and "error_description" fields inside of it though, so it might be better to align things in that direction instead. Do you have thoughts on which is preferable? 

Interop testing of error conditions is really difficult in practice, so this is a great catch!
