### ISSUE TITLE
Interaction considerations

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#81]
§4 Interaction at the AS: Editor's note: 

There are some privacy and security considerations here but for the most part we don't want to be overly prescriptive about the UX, I think.

**Comment by jricher** [comment]
Editors suggest closing, privacy considerations are needed on a number of items and will be addressed in the privacy considerations section.

**Comment by yaronf** [comment]
Yes, but you could also add some placeholder text in the Privacy Considerations while closing this issue.

**Comment by aaronpk** [comment]
Closing, tracking future discussion here: #133
