### ISSUE TITLE
Use of hash with unique callback URL

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#84]
§4.4.3 Calculating the interaction hash: Editor's note: 

If the client uses a unique callback URL per request, that prevents some of the same attacks, but without the same cryptographic binding between the interaction and delegation channels. A unique URI would allow the client to differentiate inputs, but it would not prevent an attacker from injecting an unrelated interaction reference into this channel.

**Comment by jricher** [comment]
Because of the discussion on #55, unique URIs are not required. As a result, if the hash is not required then we need to explain when the combination of the two are required, which is more fragile. Additionally, we suspect the hash still adds value on top of unique callback URIs, but this is not yet formally proven.

Editors recommend closing this issue, keeping the requirement of calculating, presenting, and verifying the hash.

**Comment by dickhardt** [comment]
Please elaborate on the injection attack.

**Comment by dickhardt** [comment]
It is not clear what attacks the hash mechanism prevents. As the client authenticates to the AS on its first call, the AS knows it is the same client later. If an attacker can obtain the unique URL and inject it into another session, they can do the same with a URL that contains a hash..

**Comment by aaronpk** [comment]
Clearly a formal assessment of this is needed, as part of #135. At that point, any features that don't add to the security of the model can be removed. The editors aren't comfortable removing this feature, especially when removing it adds optionality to the spec, prior to a formal analysis.
