### ISSUE TITLE
Key rotation within continuation

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#85]
§5 Continuing a Grant Request: Editor's note: 

We need to have a secure way to rotate the key used for the continuation here. In most cases this will be a rotation for the client instance, since a client without an instance record would likely just present a new key for a new request. In that case it could go with the client management, above - but it doesn't necessarily have to be.

**Comment by TomCJones** [comment]
See my comment on issue above
I think we need to find a single rotation recovery method.
I collected my ideas here: https://tcwiki.azurewebsites.net/index.php?title=Recovery#Proposed_for_Standardization

**Comment by fimbault** [comment]
This is close to what I was thinking about. I would also add as a reference what [KERI](https://github.com/decentralized-identity/keri) is doing on key rotation, for discussion purposes.

**Comment by jricher** [comment]
Key rotation is now handled on the continuation access token, not as part of the grant update. See #435

**Comment by adeinega** [comment]
Could you answer on https://github.com/ietf-wg-gnap/gnap-core-protocol/pull/435#issuecomment-1264060859 and other comments in this PR? Thank you.

**Comment by fimbault** [comment]
what do you mean by "more or less gracefully" ?

**Comment by adeinega** [comment]
@fimbault, you can omit "more or less gracefully", I wanted to know if GNAP allows to address the use case I provided

> It could be useful when there are multiple running instances of the client and it's tough, or even impossible, to update the keys on all these instances immediately (just as an example, the client instance could be deployed as a service in K8S).

and

> am I right that previous_key becomes immediately invalid?

**Comment by fimbault** [comment]
Indeed the idea currently is that previous-key is replaced by the new key, for all what's coming afterwards.
I know of some systems that allow a delay during which both versions coexist, is that what you're after ?

**Comment by adeinega** [comment]
There are plenty of systems where both, or even more versions coexist until an administrator or a client itself decides to remove/invalidate previous keys. That's correct.

The same approach arguably is even way more valuable for [RSs](https://github.com/ietf-wg-gnap/gnap-resource-servers/). BTW, are you planning to allow them to rotate their own keys? 

You are writing these specs, and IMO, you still have time to add & embed these features into the core of GNAP.
