### ISSUE TITLE
Default polling wait time

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#86]
§5 Continuing a Grant Request: Editor's note: 

What's a reasonable amount of time to wait by default so as not to DOS the server if the field is missing?

**Comment by fimbault** [comment]
Might have to broaden the perspective and provide more general guidance on how to avoid/limit DDoS

**Comment by jricher** [comment]
I think we need general considerations as well, but this is a specific case where a naive implementation could accidentally DoS the system by polling too quickly.

**Comment by fimbault** [comment]
yes. Then it's simple, anything around the minute should work.

**Comment by jricher** [comment]
Need to add this to the interaction response section. I suggest "SHOULD NOT be less than five seconds" and "omission MUST NOT be treated as zero".
