### ISSUE TITLE
Rotation of continuation access tokens

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#87]
§5 Continuing a Grant Request: Editor's note: 

> If the continuation was previously bound to an access token, the new continue response MUST include a bound access token as well, and this token SHOULD be a new access token. 

This used to be a MUST, but is it safe to back off that requirement?

**Comment by fimbault** [comment]
See also issue #147 (should we rotate them)

**Comment by jricher** [comment]
Token lifecycle is up to the AS. The client needs to be able to deal with a new continuation access token on every request if necessary, but there's not a compelling reason for the AS to always do this.
