### ISSUE TITLE
Multi-step interaction methods

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#89]
§5.1 Continuing After a Completed Interaction: Editor's note:

> The response SHOULD NOT contain any interaction responses. 

This last one might be overly restrictive, since some kinds of interaction could require multiple round trips. We need more examples and experience beyond redirect-based interaction here.

**Comment by fimbault** [comment]
Could we have the case that there are several ROs for several RSs (and several token labels) ? Then I suppose it could be managed either through a parallel flow or a sequential flow.  
In that sense, it's very similar to a workflow engine, with the caveat that we want to securely exchange with several parties. The most practical way of implementing that is through messaging (for instance DIDComm, which was a possibility discussed in oauth.xyz).

Also depends what we call "completed interaction" (I think it would mean that all these steps are finished -> the end of the workflow), in that case beyond this point we would indeed not have further interaction responses.

**Comment by jricher** [comment]
This is now better handled by the state model and with interaction start/finish sets having a timeout and usage pattern.
