### ISSUE TITLE
Enforcing modification of a request

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#92]
§5.2 Modifying an Existing Request: Editor's note: 

We could state something like "resources and subject MUST NOT be the same as in the initial or previous request" to enforce that this really is a change, but is there value in calling that out here? Somehow we do probably want to tell the AS to not let a client simply post the same request here to rotate access tokens now that we've got an explicit function for that, right?

**Comment by jricher** [comment]
I don't think it's a meaningful distinction to make from the client's perspective; suggest adding additional text about differentiating between grant PATCH and access token rotation (new token vs. rotated token) and close in favor of #353

**Comment by fimbault** [comment]
I think we can close this
