### ISSUE TITLE
Revoking existing access tokens on modification

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#96]
§5.3 Modifying an Existing Request: Editor's note: 

This might be subject to the "multi_token" flag, but since we're creating a NEW access token and not rotating an existing one, this seems to be a different use case.

There is a solid argument to be made for always revoking old access tokens here, but we need more discussion on the boundaries for such a requirement. If they stick around, it does make a "read" request weird because now we've got multiple access tokens sticking around associated with a grant request and no good place to put them.

**Comment by aaronpk** [comment]
I don't think we should put a strict requirement on revoking old access tokens, since it may be difficult or impossible in some implementations. At most this could be a "SHOULD" or "RECOMMENDED".
