### ISSUE TITLE
Reading the state of a request

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#98]
§5.4 Getting the Current State of a Grant Request: Editor's note: 

I'm a little dubious about the need for this particular function in reality, but including it for completeness sake. There are a lot of questions we need to answer, such as whether it's safe to include access tokens and claims in the response of this kind of "read" at all, and whether it makes sense to include items like interaction nonces in the response. This discussion should be driven by the use cases calling for this "read" functionality. There have been similar functions within proprietary protocols where the client calls an endpoint at the AS to figure out where the user is in the interaction process at the AS, letting the client provide a smarter UI. It doesn't seem like we could do that in depth here since it would be highly application specific, but that might be a good example of how to extend a response and give a client extra information.

**Comment by jricher** [comment]
Editors suggest this section requires additional text to explain why this action is needed and under what circumstances. Without additional text, this section will be removed in a future update.

**Comment by fimbault** [comment]
Closing the issue following the merge of the PR
