### ISSUE TITLE
Updating and reading access tokens

### ISSUE THREAD

**Issue by jricher** [ietf-wg-gnap/gnap-core-protocol#99]
§6 Token Management: Editor's note: 

Should we allow for "update" to an access token by the client posting new information from a "request"? It seems this might make things weird since an access token is generally considered an unchanging thing, and the client could always request a new access token if they're allowed to continue the grant request post-issuance as in Section 5.3. There's also a possibility of being able to "read" a token's state with a GET, much like token introspection but using the token's/client's key instead of the RS key. But would a client need to "read" a token state after issuance? Is there a security risk to offering that functionality? Introspection is nearly always relegated to RS calls in practice since the client is focused on using the token at the RS. The client can always read the state of the grant itself, separately.

**Comment by jricher** [comment]
See also discussion on "read" action at #98

**Comment by fimbault** [comment]
Tokens are meant to be immutable. So update is not in the scope of what we want to do. 
Read access: we don't see any compelling reason to allow read access + might be an issue for privacy. Please clarify how the mecanism would work, especially with privacy considerations. 

Marked as need text. Without additional text, this section will be removed in a future update.

**Comment by fimbault** [comment]
Closing the issue following the merge of the PR
